---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。 
---
= アップグレード中にシステムが受ける影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード中に StorageGRID システムがどのような影響を受けるかを理解しておく必要があります。



== StorageGRID のアップグレードは無停止で実行されます

StorageGRID システムは、アップグレードプロセス中もクライアントアプリケーションからデータを取り込み、読み出すことができます。同じタイプのすべてのノード（ストレージノードなど）のアップグレードを承認すると、ノードが一度に1つずつ停止されるため、すべてのグリッドノードまたは特定のタイプのすべてのグリッドノードが使用できなくなる時間はありません。

継続的な可用性を確保するには、各オブジェクトの複数のコピーを格納するように指定するルールをILMポリシーに含めるようにしてください。また、次のいずれかに要求を送信するようにすべての外部の S3 または Swift クライアントを設定する必要があります。

* ハイアベイラビリティ（HA）グループの仮想IPアドレス
* 高可用性のサードパーティ製ロードバランサ
* 各クライアントに複数のゲートウェイノードが必要
* クライアントごとに複数のストレージノード




== アプライアンスファームウェアがアップグレードされている

StorageGRID 11.7へのアップグレード時：

* すべてのStorageGRID アプライアンスノードは、StorageGRID アプライアンスインストーラのファームウェアバージョン3.7に自動的にアップグレードされます。
* SG6060およびSGF6024アプライアンスは、BIOSファームウェアバージョン3B07.EXおよびBMCファームウェアバージョン3.97.07に自動的にアップグレードされます。
* SG100およびSG1000アプライアンスは、BIOSファームウェアバージョン3B12.ECおよびBMCファームウェアバージョン4.71.07に自動的にアップグレードされます。




== アラートがトリガーされる可能性があります

アラートは、サービスの開始と停止、および StorageGRID システムを複数バージョンが混在した環境で使用している場合（一部のグリッドノードで以前のバージョンを実行し、その他のノードはより新しいバージョンにアップグレードしている場合）にトリガーされることがあります。アップグレードの完了後にその他のアラートがトリガーされることがあります。

たとえば、サービスが停止しているときに* Unable to communicate with node *アラートが表示されたり、一部のノードがStorageGRID 11.7にアップグレードされ、他のノードで引き続きStorageGRID 11.6が実行されているときに* Cassandra communication error *アラートが表示されたりすることがあります。通常、これらのアラートはアップグレードが完了するとクリアされます。

StorageGRID 11.7へのアップグレード中にストレージノードが停止すると、* ILM placement unachievable *アラートがトリガーされることがあります。このアラートは、アップグレードの完了後 1 日続く場合があります。

アップグレードが完了したら、Grid Managerダッシュボードで*[最近解決されたアラート]*または*[現在のアラート]*を選択して、アップグレード関連のアラートを確認できます。



== 多数の SNMP 通知が生成されます

アップグレード中にグリッドノードが停止および再起動されると、多数の SNMP 通知が生成される場合があります。過剰な通知を回避するには、* SNMPエージェント通知を有効にする*チェックボックス（*設定*>*監視*>* SNMPエージェント*）をオフにして、アップグレードを開始する前にSNMP通知を無効にします。その後、アップグレードの完了後に通知を再度有効にします。



== 設定の変更は制限されています


NOTE: このリストは、特にStorageGRID 11.6からStorageGRID 11.7へのアップグレードに適用されます。別のStorageGRID リリースにアップグレードする場合は、そのリリースのアップグレード手順の制限された変更のリストを参照してください。

[ 新しい機能を有効にする *] タスクが完了するまで :

* グリッド設定を変更しないでください。
* 新しい機能を有効または無効にしないでください。たとえば、両方のStorageGRID システムがStorageGRID 11.7に更新されるまで、グリッドフェデレーション接続を作成しないでください。
* ILM設定を更新しないでください。ILM の動作が不安定になり、正常に動作しない場合があります。
* ホットフィックスの適用やグリッドノードのリカバリは行わないでください。
+

NOTE: アップグレード中にノードのリカバリが必要な場合は、テクニカルサポートにお問い合わせください。

* StorageGRID 11.7へのアップグレード中は、HAグループ、VLANインターフェイス、またはロードバランサエンドポイントを管理しないでください。
* StorageGRID 11.7へのアップグレードが完了するまで、HAグループを削除しないでください。他のHAグループの仮想IPアドレスにアクセスできなくなる可能性があります。


[* Final Upgrade Steps * （最終アップグレード手順 * ） ] タスクが完了するまで：

* 拡張手順 を実行しないでください。
* 運用停止手順 は実行しないでください。




== Tenant Managerでは、バケットの詳細を表示したりバケットを管理したりすることはできません

StorageGRID 11.7へのアップグレード中（システムが複数のバージョンが混在した環境として動作している場合）は、テナントマネージャを使用してバケットの詳細を表示したりバケットを管理したりすることはできません。Tenant Manager のバケットページには、次のいずれかのエラーが表示されます。

* 11.7へのアップグレード中は、このAPIを使用できません。
* 11.7へのアップグレード中は、Tenant Managerでバケットのバージョン管理の詳細を表示できません。


このエラーは、11.7へのアップグレードが完了すると解決します。

.回避策
11.7へのアップグレードの実行中に、Tenant Managerを使用する代わりに、次のツールを使用してバケットの詳細を表示したりバケットを管理したりします。

* バケットに対して標準のS3処理を実行するには、を使用します link:../s3/operations-on-buckets.html["S3 REST API"] または link:../tenant/understanding-tenant-management-api.html["テナント管理 API"]。
* バケットに対して StorageGRID のカスタム処理（バケットの整合性レベルの表示と変更、最終アクセス日時の更新の有効化と無効化、検索統合の設定など）を実行するには、テナント管理 API を使用します。




== TLS暗号やSSHの設定が変更される可能性があります

TLS暗号またはSSH設定を手動で変更した場合、またはノード間で一貫性がない場合、アップグレード後にすべてのノードがレガシー互換性または最新互換性に上書きされます。使用した場合 `fips-ciphers.sh` StorageGRID 11.6では、情報セキュリティ国際評価基準ポリシーがすべてのノードに適用されます。それ以外の場合は、レガシー互換性ポリシーが適用されます。情報セキュリティ国際評価基準で検証された構成が必要な場合は、情報セキュリティ国際評価基準ポリシーまたはFIPS厳格ポリシーを使用する必要があります。使用しなかった場合 `fips-ciphers.sh`を使用する場合は、アップグレードの完了後に新しい最新の互換性設定を使用する必要があります。暗号を設定するには、*[設定]*>*[セキュリティ]*[セキュリティ設定]*に移動し、* TLSおよびSSHポリシー*を選択します。



== CLBポートはロードバランサエンドポイントに変換されることがあります

従来の接続ロードバランサ（CLB）サービスは、StorageGRID 11.7で削除されました。アップグレードの事前確認でCLB設定が検出されると、* Legacy CLB load balancer activity detected *アラートがトリガーされます。既存のStorageGRID バージョンでS3またはSwift API用のカスタム証明書が設定されている場合は、StorageGRID 11.7へのアップグレード時にCLBポート8082、8083、8084、および8085がロードバランサエンドポイントに変換されます。

も参照してください link:../admin/managing-load-balancing.html["ロードバランシングに関する考慮事項"]。
