---
permalink: upgrade/obtaining-required-materials-for-software-upgrade.html 
sidebar: sidebar 
keywords: upgrade, requirements, rhel, red hat, linux, centOS, ubuntu, debian 
summary: ソフトウェアのアップグレードを開始する前に、アップグレードを正常に完了できるよう、必要なファイル、機器、情報をすべて揃えておく必要があります。 
---
= ソフトウェアのアップグレードに必要なファイル、機器、機器を揃えます
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェアのアップグレードを開始する前に、アップグレードを正常に完了できるよう、必要なファイル、機器、情報をすべて揃えておく必要があります。

[cols="1a,3a"]
|===
| 項目 | 注： 


 a| 
サービスラップトップ
 a| 
サービスラップトップには次のものが必要です。

* ネットワークポート
* SSH クライアント（ PuTTY など）




 a| 
link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]
 a| 
通常、ブラウザサポートは StorageGRID リリースごとに変更されます。ブラウザが新しい StorageGRID バージョンに対応していることを確認します。



 a| 
プロビジョニングパスフレーズ
 a| 
このパスフレーズは、 StorageGRID システムが最初にインストールされるときに作成されて文書化されます。プロビジョニングパスフレーズは、に表示されません `Passwords.txt` ファイル。



 a| 
Linux RPMまたはDEBアーカイブ
 a| 
Linuxホストにノードが導入されている場合は、を実行する必要があります link:linux-installing-rpm-or-deb-package-on-all-hosts.html["RPMパッケージまたはDEBパッケージをすべてのホストにダウンロードしてインストールします"] アップグレードを開始する前に、

*重要*:オペレーティングシステムがLinuxカーネル4.15以降にアップグレードされていることを確認してください。



 a| 
StorageGRID のドキュメント
 a| 
* link:../release-notes/index.html["リリースノート"] StorageGRID 11.7の場合（サインインが必要）。アップグレードを開始する前に、このドキュメントに記載されている情報をよくお読みください。
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/StorageGRID_software_upgrade_resolution_guide["StorageGRID ソフトウェアアップグレード解決ガイド"^] アップグレード先のメジャーバージョン（サインインが必要）
* その他 https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID 11.7ドキュメント"^]、必要に応じて。


|===