---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 11.7 
summary: このリリースの StorageGRID には、次の機能が導入されています。 
---
= StorageGRID 11.7の新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このリリースのStorageGRID では、次の機能変更が導入されています。



== 新機能



=== グリッドフェデレーション

ディザスタリカバリ用に、2つのStorageGRID システム間のグリッドフェデレーション接続を設定して、テナントアカウント情報をクローニングし、グリッド間でバケットオブジェクトをレプリケートすることができます。を参照してください link:../admin/grid-federation-overview.html["グリッドフェデレーションとは"]、 link:../admin/grid-federation-what-is-account-clone.html["アカウントクローンとは何ですか"]および link:../admin/grid-federation-what-is-cross-grid-replication.html["クロスグリッドレプリケーションとは"]。



=== 読み取りの可用性が向上します

read-after-new-write（デフォルト）整合性制御が強化され、より可用性が高くなりました。新規オブジェクトに対するGET / HEAD要求は、各サイトで最大1つのストレージノードがオフラインになると成功します。このシナリオでは、バケットをavailable整合性制御に設定する必要がなくなりました。たとえば、作成前にオブジェクトの存在をチェックするアプリケーションは、ソフトウェアのアップグレード時に1つのストレージノードがオフラインの場合でもread-after-new-writeで正常に機能します。



=== グリッド、サイト、ノードの名前を変更します

新しいメンテナンス手順 では、グリッドマネージャ全体に表示される表示名を変更できます。表示名は、必要なときに安全に更新できます。を参照してください link:../maintain/rename-grid-site-node-overview.html["グリッド、サイト、ノードの名前を変更します"]。



=== FabricPool とS3のセットアップウィザード

FabricPool およびS3のセットアップウィザードの手順に従って、ONTAP FabricPool またはその他のS3クライアントアプリケーションで使用するStorageGRID を設定します。また、もう一方のアプリケーションで必要な値を入力するときに使用できるファイルが生成されます。を参照してください link:../fabricpool/use-fabricpool-setup-wizard.html["FabricPool セットアップウィザードを使用する"] および link:../admin/use-s3-setup-wizard.html["S3セットアップウィザードを使用する"]。

この変更に関連して、新しいユーザに設定を促すバナーがダッシュボードに表示されるようになりました link:../admin/configuring-s3-api-endpoint-domain-names.html["S3エンドポイントのドメイン名"] （S3仮想ホスト形式の要求とセットアップ） link:../monitor/email-alert-notifications.html["アラートのEメール通知"]。



=== ファイアウォールコントロール

[Firewall control]ページでは、グリッド内のノード上のポートの外部アクセスを管理したり、閉じたポートへのアクセスを許可するホストアドレスとIPサブネットを定義したりできます。新しいページには[Untrusted Client Network]の設定も含まれており、信頼されていないクライアントネットワークが設定されたときに開く追加のポートを選択できるようになりました。を参照してください link:../admin/configure-firewall-controls.html["内部ファイアウォールを設定します"]。



=== 強化されたセキュリティポリシー

クライアントアプリケーションとのセキュアなTLS接続の確立や内部StorageGRID サービスへのセキュアなSSH接続に使用されるプロトコルと暗号を確認できるようになりました。を参照してください link:../admin/manage-tls-ssh-policy.html["TLSおよびSSHポリシーを管理します"]。



=== ロードバランサエンドポイントの変更

いつ link:../admin/configuring-load-balancer-endpoints.html["ロードバランサエンドポイントを設定しています"]では、次の操作を実行できます。

* すべてのテナントにエンドポイントへのアクセスを許可するか（デフォルト）、許可またはブロックされたテナントのリストを指定してテナントとそのエンドポイント間のセキュリティ分離を強化します。
* 選択したノードのタイプに基づいて、任意の管理ノードのIPアドレス（または対応するFQDN）またはゲートウェイノードのIPアドレスの使用をクライアントに要求するには、* Node Type *バインドモードを使用します。




== SGF6112オールフラッシュアプライアンス

新しいStorageGRID SGF6112ストレージアプライアンスは、1Uシャーシにコンピューティングコントローラとストレージコントローラを統合したコンパクトな設計を特徴としています。アプライアンスは12本のSSD NVMeドライブをサポートし、ドライブあたり最大15.3TBのストレージ容量を実現します。SSDドライブは、耐障害性に優れたオブジェクトストレージを提供するRAIDに組み込まれています。を参照してください link:../installconfig/hardware-description-sg6100.html["SGF6112アプライアンス：概要"]。



== Grid Manager に関するその他の機能拡張



=== ILMの機能拡張

改良されたILMウィザードでは、フィルタの指定、期間と配置の入力、保持図の表示が簡単になりました。イレイジャーコーディングプロファイルは、配置用のストレージプールとECスキームを選択すると自動的に作成されます。StorageGRID 11.7の新規インストール（アップグレードではない）では、サイトごとにストレージプールが自動的に作成され、新しい[* 1 Copy per Site]デフォルトルールにより、新しいマルチサイトインストールではデフォルトでサイト障害から保護されます。を参照してください link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]。



=== カスタマイズ可能なダッシュボード

Grid Manager用のカスタムダッシュボードを設定できるようになりました。を参照してください link:../monitor/viewing-dashboard.html["ダッシュボードを表示および管理します"]。



=== ボリュームリストア用のUI

ストレージボリュームのリストアでは、ストレージボリュームで障害が発生した場合にオブジェクトデータをリストアできます。StorageGRID 11.7では、既存のコマンドを手動で入力する方法に加えて、Grid Managerからボリュームのリストアを開始できます。オブジェクトデータのリストアには、Grid Managerを使用することを推奨します。を参照してください link:../maintain/restoring-volume.html["Grid Managerを使用してオブジェクトデータをリストアする"]。



=== アップグレードとホットフィックスのUI

StorageGRID 11.7にアップグレードする場合は、最新の11.7ホットフィックスを同時に適用できます。StorageGRID のアップグレードページに推奨されるアップグレードパスが表示され、正しいダウンロードページへのリンクが直接表示されます。を参照してください link:performing-upgrade.html["アップグレードを実行する"]。



=== ストレージ値の単位

Grid ManagerとTenant Managerに表示されるストレージの値に10進法または2進法の単位を選択できるようになりました。Grid ManagerまたはTenant Managerの右上にあるユーザドロップダウンを選択し、*[User preferences]*を選択します。



=== Grid ManagerからMIBにアクセスします

Grid Managerの[SNMP agent]ページを使用して、SNMP準拠のMIBファイルにアクセスできるようになりました。を参照してください link:../monitor/access-snmp-mib.html["MIBファイルにアクセスします"]。



=== 新しいノード用のカスタムストレージグレード

拡張を実行して新しいサイトまたは新しいストレージノードを追加するときに、新しいノードごとにカスタムのストレージグレードを割り当てることができるようになりました。を参照してください link:../expand/performing-expansion.html["拡張を実行"]。



== テナントマネージャが更新されます



=== グリッド間レプリケーション

を使用する権限を持つテナントアカウント <<grid-federation,グリッドフェデレーション接続>> テナントグループ、ユーザ、S3キーをグリッド間でクローニングし、グリッド間レプリケーションを使用して2つのグリッド間でバケットオブジェクトをレプリケートできます。を参照してください link:../tenant/grid-federation-account-clone.html["テナントグループとテナントユーザのクローンを作成します"] および link:../tenant/grid-federation-manage-cross-grid-replication.html["グリッド間レプリケーションを管理します"]。



=== バケットからすべてのオブジェクトを削除する

Tenant Managerユーザがバケット内のすべてのオブジェクトを削除してバケットを削除できるようになりました。を参照してください link:../tenant/deleting-s3-bucket-objects.html["バケット内のオブジェクトを削除する"]。



=== S3オブジェクトロックのデフォルトの保持期間

テナントManagerユーザが、S3オブジェクトロックバケットの作成時にデフォルトの保持期間を有効にして設定できるようになりました。を参照してください link:../tenant/creating-s3-bucket.html["S3 バケットを作成します。"]。



== S3の更新



=== S3オブジェクトロックガバナンスモード

オブジェクトのS3オブジェクトロック設定やバケットのデフォルトの保持設定を指定する際に、ガバナンスモードを使用できるようになりました。この保持モードでは、特別な権限を持つユーザが特定の保持設定をバイパスできます。を参照してください link:../tenant/using-s3-object-lock.html["S3オブジェクトロックを使用してオブジェクトを保持します"] および link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST APIを使用してS3オブジェクトロックを設定します"]。



=== ランサムウェアを軽減するためのS3グループポリシー

このサンプルポリシーをS3テナントアカウントのグループポリシーとして追加すると、ランサムウェア攻撃の軽減に役立ちます。古いオブジェクトバージョンが完全に削除されるのを防ぐことができます。を参照してください link:../tenant/creating-groups-for-s3-tenant.html["S3 テナント用のグループを作成します"]。



=== S3バケットのNewerNoncurrentVersionsしきい値

。 `NewerNoncurrentVersions` バケットライフサイクル設定の処理は、バージョン管理されたS3バケットで保持する最新でないバージョンの数を指定します。このしきい値は、ILMのライフサイクルルールよりも優先されます。を参照してください link:../ilm/how-objects-are-deleted.html["オブジェクトの削除方法"]。



=== S3 Selectの更新を選択します

S3 SelectObjectContentで寄木細工オブジェクトがサポートされるようになりました。また、cgroup v2が有効なカーネルを実行するベアメタルノードであるAdminおよびGatewayのロードバランサエンドポイントでS3 Selectを使用できるようになりました。を参照してください link:../s3/select-object-content.html["S3 SelectObjectContentの略"]。



== その他の機能強化



=== 証明書のサブジェクトはオプションです

証明書のサブジェクトフィールドはオプションになりました。このフィールドを空白のままにすると、生成された証明書では、最初のドメイン名またはIPアドレスがサブジェクト共通名（CN）として使用されます。を参照してください link:../admin/using-storagegrid-security-certificates.html["セキュリティ証明書を管理する"]。



=== ILM監査メッセージカテゴリと新しいメッセージ

ILM処理用の監査メッセージカテゴリが追加され、IDEL、LKCU、およびORLMメッセージが含まれます。この新しいカテゴリは* Normal *に設定されます。を参照してください link:../audit/ilm-audit-messages.html["ILM処理の監査メッセージ"]。

また、11.7の新しい機能をサポートするために、次の新しい監査メッセージが追加されました。

* link:../audit/bror-bucket-read-only-request.html["BROR：バケット読み取り専用要求"]
* link:../audit/cgrr-cross-grid-replication-request.html["CGRR：クロスグリッドレプリケーション要求"]
* link:../audit/ebdl-empty-bucket-delete.html["EBDL：空のバケット削除"]
* link:../audit/ebkr-empty-bucket-request.html["EBKR：バケット要求が空です"]
* link:../audit/s3-select-request.html["S3SL：S3 [Request]を選択します"]




=== 新しいアラート

StorageGRID 11.7で追加された新しいアラートは次のとおりです。

* アプライアンスのDASドライブ障害が検出されました
* アプライアンスDASドライブのリビルド
* アプライアンスのファン障害が検出されました
* アプライアンスNICの障害が検出されました
* アプライアンスSSDの重大な警告です
* AutoSupport メッセージの送信に失敗しました
* Cassandraオーバーサイズ書き込みエラー
* クロスグリッドレプリケーションの永続的な要求が失敗しました
* グリッド間レプリケーションリソースを使用できません
* パフォーマンスへの影響をデバッグします
* グリッドフェデレーション証明書の有効期限
* FabricPool バケットにサポート対象外のバケット整合性設定があります
* ファイアウォールの設定に失敗しました
* グリッドフェデレーション接続に失敗しました
* ストレージアプライアンスのファンで障害が検出されました
* ストレージノードが目的のストレージ状態ではありません
* ストレージボリュームで対応が必要です
* ストレージボリュームをリストアする必要があります
* ストレージボリュームはオフラインです
* トレース設定が有効になりました
* ボリュームのリストアでレプリケートデータの修復を開始できませんでした




=== ドキュメントの変更

* StorageGRID でのAmazon Simple Storage Service（S3）APIのサポート方法をまとめた新しいクイックリファレンスです。を参照してください link:../s3/quick-reference-support-for-aws-apis.html["クイックリファレンス：サポートされるS3 API要求"]。
* 新しい link:../primer/quick-start.html["StorageGRID クイックスタート"] に、StorageGRID システムを設定および使用する手順の概要と、関連する手順へのリンクを示します。
* 使いやすいように、アプライアンスハードウェアの設置手順が統合されました。ハードウェア設置の概要ガイドとしてクイックスタートが追加されました。を参照してくださいlink:../installconfig/index.html["ハードウェア設置のクイックスタート"]。
* すべてのアプライアンスモデルに共通のメンテナンス手順が統合され、ドキュメントサイトのメンテナンスセクションに移動されました。を参照してください link:../commonhardware/index.html["共通ノードのメンテナンス：概要"]。
* 各アプライアンスモデルに固有のメンテナンス手順もメンテナンスセクションに移動しました。
+
link:../sg6100/index.html["SGF6112ハードウェアのメンテナンス"]

+
link:../sg6000/index.html["SG6000ハードウェアのメンテナンス"]

+
link:../sg5700/index.html["SG5700ハードウェアのメンテナンス"]

+
link:../sg100-1000/index.html["SG100およびSG1000ハードウェアのメンテナンス"]


