---
permalink: sg100-1000/shut-down-sg1000.html 
sidebar: sidebar 
keywords: storagegrid, sg1000, SG100, power off, turn off, shut off, shutdown, shut down, 
summary: サービスアプライアンスをシャットダウンして、ハードウェアのメンテナンスを行います。 
---
= サービスアプライアンスをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスアプライアンスをシャットダウンして、ハードウェアのメンテナンスを行います。

.作業を開始する前に
* これで完了です link:locating-controller-in-data-center.html["サービスアプライアンスを物理的に設置します"]。


.このタスクについて
サービスの中断を回避するには、通常、サービスの中断が予想される時間帯に、スケジュールされたメンテナンス期間中にサービスアプライアンスをシャットダウンします。

.手順
. アプライアンスをシャットダウンします。
+

CAUTION: 次のコマンドを入力して、アプライアンスの制御シャットダウンを実行する必要があります。不要なアラートを回避し、フルログを利用できることを確認し、サービスの停止を回避するために、可能なかぎり通常の方法でシャットダウンすることを推奨します。

+
.. PuTTY または別の SSH クライアントを使用して、グリッドノードにログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. サービスアプライアンスをシャットダウンします。+
`*shutdown -h now*`
+
このコマンドの実行には 10 分程度かかる場合があります。



. 次のいずれかの方法で、アプライアンスの電源がオフになっていることを確認します。
+
** アプライアンス前面の電源 LED を調べて、消灯していることを確認します。
** BMC インターフェイスの電源制御ページで、アプライアンスがオフになっていることを確認します。



