---
permalink: installconfig/connecting-power-cords-and-applying-power-sg6000.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, wire, wiring, cabling, cable, Connecting, connect, power cords, power, applying power, apply power, turn on, power up, ac, ac power 
summary: ネットワークケーブルを接続したら、 SG6000-CN コントローラと 2 台のストレージコントローラまたはオプションの拡張シェルフの電源を入れることができます。 
---
= 電源コードを接続して電源（ SG6000 ）を投入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークケーブルを接続したら、 SG6000-CN コントローラと 2 台のストレージコントローラまたはオプションの拡張シェルフの電源を入れることができます。

.手順
. ストレージコントローラシェルフの両方のコントローラがオフになっていることを確認します。
+

CAUTION: * 感電の危険性 * -- 電源コードを接続する前に、 2 台の各ストレージコントローラの電源スイッチがオフになっていることを確認してください。

. 拡張シェルフがある場合は、両方の IOM の電源スイッチがオフになっていることを確認します。
+

CAUTION: * 感電の危険性 * -- 電源コードを接続する前に、各拡張シェルフの 2 つの電源スイッチがオフになっていることを確認してください。

. SG6000-CN コントローラの 2 つ電源装置のそれぞれに電源コードを接続します。
. これらの 2 本の電源コードを、キャビネットまたはラック内の別々の配電ユニット（ PDU ）に接続します。
. ストレージコントローラシェルフの 2 つ電源装置のそれぞれに電源コードを接続します。
. 拡張シェルフがある場合は、各拡張シェルフの 2 つ電源装置のそれぞれに電源コードを接続します。
. 各ストレージシェルフ（オプションの拡張シェルフを含む）の 2 本の電源コードを、キャビネットまたはラック内の別々の PDU に接続します。
. SG6000-CN コントローラの前面にある電源ボタンが青色に点灯していない場合は、ボタンを押してコントローラの電源をオンにします。
+
電源投入プロセス中に電源ボタンを再度押さないでください。

. ストレージコントローラシェルフの背面にある 2 つの電源スイッチをオンにします。拡張シェルフがある場合は、各シェルフの 2 つの電源スイッチをオンにします。
+
** 電源投入プロセス中は、電源スイッチをオフにしないでください。
** ストレージコントローラシェルフとオプションの拡張シェルフのファンは、初回起動時に大きな音を立てることがあります。起動時に大きな音がしても問題はありません。


. コンポーネントが起動したら、ステータスを確認します。
+
** 各ストレージコントローラの背面のデジタル表示ディスプレイを確認します。詳細については、起動時のステータスコードの表示に関する記事を参照してください。
** SG6000-CN コントローラの前面にある電源ボタンが点灯していることを確認します。


. エラーが発生した場合は、問題を修正します。
. 前面ベゼルを取り外してある場合は、 SG6000-CN コントローラに取り付けます。


.関連情報
* link:viewing-status-indicators.html["ステータスインジケータを表示します"]
* link:../sg6000/reinstalling-sg6000-cn-controller-into-cabinet-or-rack.html["SG6000-CN コントローラをキャビネットまたはラックに再度取り付けます"]

