---
permalink: installconfig/reviewing-appliance-network-connections.html 
sidebar: sidebar 
keywords: network connections, appliance, grid, admin, client, bmc, management 
summary: StorageGRID アプライアンスを設置する前に、アプライアンスに接続できるネットワークを確認しておく必要があります。 
---
= アプライアンスのネットワーク接続を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID アプライアンスを設置する前に、アプライアンスに接続できるネットワークを確認し、各コントローラのポートがどのように使用されるかを把握する必要があります。StorageGRID のネットワーク要件については、を参照してください link:../network/index.html["ネットワークのガイドライン"]。

StorageGRID アプライアンスを StorageGRID システムのノードとして導入する場合は、次のネットワークに接続できます。

* * StorageGRID のグリッドネットワーク * ：グリッドネットワークは、すべての内部 StorageGRID トラフィックに使用されます。このネットワークによって、グリッド内のすべてのノードが、すべてのサイトおよびサブネットにわたって相互に接続されます。グリッドネットワークは必須です。
* * StorageGRID の管理ネットワーク * ：管理ネットワークは、システムの管理とメンテナンスに使用するクローズドネットワークです。管理ネットワークは通常はプライベートネットワークであり、サイト間でルーティング可能にする必要はありません。管理ネットワークはオプションです。
* * StorageGRID のクライアントネットワーク： * クライアントネットワークは、 S3 や Swift などのクライアントアプリケーションへのアクセスを可能にするオープンネットワークです。クライアントネットワークはグリッドへのクライアントプロトコルアクセスを提供するため、グリッドネットワークを分離してセキュリティを確保できます。開くことを選択したポートだけを使用してこのネットワーク経由でアプライアンスにアクセスできるよう、クライアントネットワークを設定できます。クライアントネットワークはオプションです。
* * SANtricity の管理ネットワーク*（ストレージアプライアンスではオプション。SGF6112では不要）：このネットワークからSANtricity System Managerにアクセスして、アプライアンスおよびストレージコントローラシェルフのハードウェアコンポーネントの監視と管理を行うことができます。この管理ネットワークは、 StorageGRID の管理ネットワークと同じにすることも、独立した管理ネットワークにすることもできます。
* * BMC管理ネットワーク*（SG100、SG1000、SG6000、SGF6112の場合はオプション）：SG100、SG1000、SG6000、SGF6112アプライアンスのベースボード管理コントローラにアクセスして、アプライアンスのハードウェアコンポーネントの監視と管理を行うことができます。この管理ネットワークは、 StorageGRID の管理ネットワークと同じにすることも、独立した管理ネットワークにすることもできます。
+
オプションの BMC 管理ネットワークが接続されていないと、一部のサポート手順およびメンテナンス手順の実行が困難になります。BMC 管理ネットワークは、サポート目的で必要な場合を除き、接続しないでください。




NOTE: StorageGRID ネットワークの詳細については、を参照してください link:../network/storagegrid-network-types.html["StorageGRID のネットワークタイプ"]。
