---
permalink: swift/recommendations-for-implementing-swift-rest-api.html 
sidebar: sidebar 
keywords: implement swift rest api 
summary: StorageGRID で使用するために Swift REST API を実装する場合は、次の推奨事項を考慮してください。 
---
= Swift REST API を実装する際の推奨事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID で使用するために Swift REST API を実装する場合は、次の推奨事項を考慮してください。



== 存在しないオブジェクトに対する HEAD の推奨事項

オブジェクトが実際に存在するとは思わないパスにオブジェクトが存在するかどうかをアプリケーションが定期的にチェックする場合は、「使用可能」整合性制御を使用する必要があります。たとえば ' アプリケーションがそのロケーションに対して PUT 操作を実行する前に ' そのロケーションに対して HEAD 操作を実行する場合は ' Available 整合性制御を使用する必要があります

そうしないと、使用できないストレージノードがある場合に HEAD 処理でオブジェクトが見つからないと、「 500 Internal Server Error 」が大量に返される可能性があります。

を使用して、各コンテナに「使用可能」の整合性制御を設定できます link:put-container-consistency-request.html["PUT コンテナセイコウセイヨウキユウ"]。を使用して、各コンテナの整合性制御を「使用可能」に設定します link:get-container-consistency-request.html["GET コンテナセイコウセイヨウキユウ"]。



== オブジェクト名の推奨事項

StorageGRID 11.4 以降で作成されたコンテナの場合、オブジェクト名がパフォーマンスのベストプラクティスに適合するように制限する必要はなくなりました。たとえば、オブジェクト名の最初の 4 文字にランダムな値を使用できるようになりました。

StorageGRID 11.4 よりも前のリリースで作成されたコンテナの場合は、オブジェクト名に関する次の推奨事項に進みます。

* オブジェクト名の最初の 4 文字に、ランダムな値を使用しないでください。これは、 AWS が以前に推奨していた名前プレフィックスの推奨とは異なります。代わりに、などの一意ではないランダムなプレフィックスを使用してください `image`。
* 名前のプレフィックスにランダムな一意の文字を使用するように AWS の以前の推奨事項に従っている場合は、オブジェクト名の前にディレクトリ名を指定する必要があります。つまり、次の形式を使用します。
+
[listing]
----
mycontainer/mydir/f8e3-image3132.jpg
----
+
次の形式は使用しないでください。

+
[listing]
----
mycontainer/f8e3-image3132.jpg
----




== 「範囲の読み取り」に関する推奨事項

状況に応じて link:../admin/configuring-stored-object-compression.html["格納オブジェクトを圧縮するグローバルオプション"] が有効になっている場合は、Swiftクライアントアプリケーションで、返されるバイト数の範囲を指定するGET Object処理を実行しないでください。StorageGRID は要求されたバイトにアクセスするためにオブジェクトを圧縮解除する必要があるため ' これらの "`range read`" 操作は非効率的です非常に大きなオブジェクトから小さい範囲のバイト数を要求する GET Object 処理は特に効率が悪く、たとえば、 50GB の圧縮オブジェクトから 10MB の範囲を読み取る処理は非常に非効率的です。

圧縮オブジェクトから範囲を読み取ると、クライアント要求がタイムアウトする可能性があります。


NOTE: オブジェクトを圧縮する必要があり、クライアントアプリケーションが範囲読み取りを使用する必要がある場合は、アプリケーションの読み取りタイムアウトを増やしてください。
