---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。 
---
= テナント管理権限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
テナントグループを作成する前に、そのグループに割り当てる権限を検討してください。テナント管理権限は、 Tenant Manager またはテナント管理 API を使用してユーザが実行できるタスクを決定します。ユーザは 1 つ以上のグループに属することができます。権限は、ユーザが複数のグループに属している場合に累積されます。

Tenant Manager にサインインするには、またはテナント管理 API を使用するには、少なくとも 1 つの権限が割り当てられたグループにユーザが属している必要があります。サインインできるすべてのユーザは、次のタスクを実行できます。

* ダッシュボードを表示します
* 自分のパスワードを変更する（ローカルユーザの場合）


すべての権限について、グループのアクセスモード設定によって、ユーザが設定を変更して処理を実行できるかどうか、またはユーザが関連する設定と機能のみを表示できるかどうかが決まります。


NOTE: ユーザが複数のグループに属していて、いずれかのグループが読み取り専用に設定されている場合、選択したすべての設定と機能に読み取り専用でアクセスできます。

グループには次の権限を割り当てることができます。S3 テナントと Swift テナントではグループの権限が異なるので注意してください。

[cols="1a,3a"]
|===
| アクセス権 | 説明 


 a| 
ルートアクセス
 a| 
Tenant Manager とテナント管理 API へのフルアクセスを提供します。

*注：* Swiftユーザがテナントアカウントにサインインするには、Root Access権限が必要です。



 a| 
管理者
 a| 
Swift テナントのみ。このテナントアカウントの Swift コンテナとオブジェクトへのフルアクセスを提供します

* 注： * Swift ユーザが Swift REST API を使用して処理を実行するには、 Swift 管理者の権限が必要です。



 a| 
自分のS3クレデンシャルを管理します
 a| 
ユーザに自分の S3 アクセスキーの作成および削除を許可します。この権限がないユーザには、* storage（S3）*>* My S3 access keys *メニューオプションが表示されません。



 a| 
すべてのバケットを管理
 a| 
* S3 テナント： S3 のバケットまたはグループポリシーに関係なく、ユーザに Tenant Manager とテナント管理 API を使用して S3 バケットの作成と削除を許可し、テナントアカウント内のすべての S3 バケットの設定を管理することを許可します。
+
この権限がないユーザーには、[バケット]メニューオプションは表示されません。

* Swift テナント： Swift ユーザにテナント管理 API を使用して Swift コンテナの整合性レベルを制御することを許可します。


*注：* Manage All Buckets権限をSwiftグループに割り当てるには、テナント管理APIを使用する必要があります。Tenant Managerを使用してSwiftグループにこの権限を割り当てることはできません。



 a| 
エンドポイントを管理します
 a| 
ユーザに、テナントマネージャまたはテナント管理APIを使用して、StorageGRID プラットフォームサービスのデスティネーションとして使用するプラットフォームサービスエンドポイントを作成または編集することを許可します。

この権限がないユーザーには、*プラットフォームサービスエンドポイント*メニューオプションは表示されません。



 a| 
S3コンソールでオブジェクトを管理します
 a| 
Manage All Buckets権限と組み合わせると、ユーザは[Buckets]ページからExperimental S3 Consoleにアクセスできるようになります。この権限はあるものの、Manage All Buckets権限がないユーザは、Experimental S3 Consoleに直接移動できます。

|===