---
permalink: vmware/planning-and-preparation.html 
sidebar: sidebar 
keywords: how to plan before installation 
summary: グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。 
---
= インストールの前に（ VMware ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッドノードの導入および StorageGRID グリッドの設定を行う前に、手順 を完了するためのステップと要件を把握しておく必要があります。

StorageGRID の導入手順と設定手順を実行するには、 StorageGRID システムのアーキテクチャと運用機能に関する十分な知識が必要です。

一度に 1 つ以上のサイトを導入できますが、ストレージノードが少なくとも 3 つ必要であるという最小要件をすべてのサイトが満たしている必要があります。

ノード導入とグリッド設定の手順 を開始する前に、次の作業を完了しておく必要があります。

* StorageGRID の導入を計画します。
* StorageGRID アプライアンスを含む必要なすべてのハードウェアを仕様に従って設置、接続、設定します。
+

IMPORTANT: StorageGRID 環境でStorageGRID アプライアンス（ハードウェア）ストレージノードを使用しない場合は、バッテリバックアップ式書き込みキャッシュ（BBWC）を備えたハードウェアRAIDストレージを使用する必要があります。StorageGRID は、Virtual Storage Area Network（VSAN;仮想ストレージエリアネットワーク）、ソフトウェアRAID、またはRAID保護なしの使用をサポートしていません。

+

NOTE: ハードウェア固有のインストールと統合の手順は、StorageGRID のインストール手順 には含まれていません。StorageGRID アプライアンスのインストール方法については、を参照してください link:../installconfig/index.html["アプライアンスハードウェアを設置"]。

* を理解します link:../network/index.html["使用可能なネットワークオプションおよび各ネットワークオプションをグリッドノードで実装する方法"]。
* すべてのネットワーク情報を事前に収集します。DHCPを使用している場合を除き、各グリッドノードに割り当てるIPアドレス、および使用するDNSサーバとNTPサーバのIPアドレスを収集します。
* 使用する導入ツールと設定ツールを決定します。

