---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords: installation materials vmware 
summary: StorageGRID をインストールする前に、必要な情報やデータ、機器を揃えておく必要があります。 
---
= 前提要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID をインストールする前に、必要な情報やデータ、機器を揃えておく必要があります。

[cols="1a,2a"]
|===
| 項目 | 注： 


 a| 
NetApp StorageGRID ライセンス
 a| 
デジタル署名された有効なネットアップライセンスが必要です。

* 注： StorageGRID インストールアーカイブには、製品サポートのない無償ライセンスが含まれています。



 a| 
StorageGRID インストールアーカイブ
 a| 
実行する必要があります link:downloading-and-extracting-storagegrid-installation-files.html["StorageGRID インストールアーカイブをダウンロードして、ファイルを展開します"]。



 a| 
VMware のソフトウェアとドキュメント
 a| 
インストール時に、 VMware vSphere Web Client を使用して仮想マシンに仮想グリッドノードを導入します。サポートされるバージョンについては、を参照してください https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^]。



 a| 
サービスラップトップ
 a| 
StorageGRID システムは、サービスラップトップを介してインストールされます。サービスラップトップには次のものが必要です。

* ネットワークポート
* SSH クライアント（ PuTTY など）
* link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]




 a| 
StorageGRID のドキュメント
 a| 
* link:../release-notes/index.html["リリースノート"]
* link:../admin/index.html["StorageGRID の管理手順"]


|===