---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 仮想マシンを使用すると、あらゆるタイプの StorageGRID グリッドノードをホストできます。VMware サーバにインストールされたグリッドノードごとに 1 つの仮想マシンが必要です。 
---
= ソフトウェア要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンを使用すると、あらゆるタイプの StorageGRID グリッドノードをホストできます。VMware サーバにインストールされたグリッドノードごとに 1 つの仮想マシンが必要です。



== VMware vSphere ハイパーバイザー

準備が整った物理サーバに VMware vSphere ハイパーバイザーをインストールする必要があります。VMware ソフトウェアをインストールする前に、ハードウェアが正しく設定されている必要があります（ファームウェアバージョンと BIOS 設定を含む）。

* インストールする StorageGRID システムのネットワークをサポートできるように、ハイパーバイザーのネットワークを設定します。
+
link:../network/index.html["ネットワークのガイドライン"]

* データストアが、グリッドノードをホストするために必要な仮想マシンと仮想ディスクに十分な大きさであることを確認します。
* 複数のデータストアを作成する場合は、仮想マシン作成時に各グリッドノードに使用するデータストアを簡単に識別できるよう、各データストアに名前を付けます。




== ESX ホストの設定要件


CAUTION: 各 ESX ホストでネットワークタイムプロトコル（ NTP ）を適切に設定する必要があります。ホストの時刻が正しくないと、データ損失などのマイナスの影響が生じる可能性があります。



== VMware の設定要件

StorageGRID グリッドノードを導入する前に、 VMware vSphere および vCenter をインストールして設定する必要があります。

サポートされるVMware vSphere HypervisorおよびVMware vCenter Serverソフトウェアのバージョンについては、を参照してください https://["NetApp Interoperability Matrix Tool で確認できます"^]。

これらの VMware 製品をインストールするために必要な手順については、 VMware のドキュメントを参照してください。
