---
permalink: admin/archiving-to-tape-through-tsm-middleware.html 
sidebar: sidebar 
keywords: tivoli storage manager, tsm server, archive node, tape 
summary: Tivoli Storage Manager サーバ（ TSM ）をターゲットとするようにアーカイブノードを構成できます。 TSM サーバは、テープライブラリを含むランダムまたはシーケンシャルアクセスのストレージデバイスとの間でオブジェクトデータを格納および読み出すための論理インターフェイスです。 
---
= TSM ミドルウェア経由でのテープへのアーカイブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tivoli Storage Manager （ TSM ）サーバをターゲットとするようにアーカイブノードを構成できます。 TSM サーバは、テープライブラリを含むランダムまたはシーケンシャルアクセスのストレージデバイスとの間でオブジェクトデータを格納および読み出すための論理インターフェイスです。

アーカイブノードの ARC サービスは TSM サーバに対するクライアントとして機能し、 Tivoli Storage Manager をアーカイブストレージシステムと通信するためのミドルウェアとして使用します。

[CAUTION]
====
アーカイブノードのサポート（S3 APIを使用してクラウドにアーカイブする場合とTSMミドルウェアを使用してテープにアーカイブする場合の両方）は廃止され、今後のリリースで削除される予定です。アーカイブノードから外部アーカイブストレージシステムへのオブジェクトの移動は、より多くの機能を提供するILMクラウドストレージプールに置き換えられました。

を参照してください link:../ilm/what-cloud-storage-pool-is.html["クラウドストレージプールを使用"]。

====


== TSM 管理クラス

TSM ミドルウェアによって定義された管理クラスは、 TSM のバックアップおよびアーカイブ処理がどのように機能するかを示します。この管理クラスを使用して、 TSM サーバによって適用されるコンテンツ用のルールを指定できます。これらのルールは StorageGRID システムの ILM ポリシーとは独立して機能します。オブジェクトは永続的に格納され、アーカイブノードによっていつでも読み出し可能であるという StorageGRID システムの要件と矛盾しないことが必要です。アーカイブノードから TSM サーバにオブジェクトデータが送信されたあと、 TSM サーバが管理するテープにオブジェクトデータが格納される間、 TSM のライフサイクルと保持のルールが適用されます。

TSM 管理クラスは、アーカイブノードから TSM サーバにオブジェクトデータが送信されたあと、データの場所または保持のルールを適用するために TSM サーバで使用されます。たとえば、データベースのバックアップとして識別されたオブジェクト（新しいデータで上書き可能な一時的コンテンツ）を、アプリケーションデータ（無期限に保持する必要のある固定コンテンツ）とは別の方法で処理できます。
