---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: browser inactivity timeout, inactive users 
summary: Grid Manager ユーザと Tenant Manager ユーザが一定期間非アクティブになった場合にサインアウトするかどうかを制御できます。 
---
= ブラウザの非アクティブタイムアウトを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Manager ユーザと Tenant Manager ユーザが一定期間非アクティブになった場合にサインアウトするかどうかを制御できます。

.作業を開始する前に
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* Root Access 権限が割り当てられている。


.このタスクについて
ブラウザの非アクティブ時のタイムアウトのデフォルトは15分です。ユーザのブラウザがこの時間アクティブでない場合、ユーザはサインアウトされます。

必要に応じて、*非アクティブなユーザーをあとでサインアウト*オプションを設定することで、タイムアウト時間を増減できます。

ブラウザの非アクティブ時のタイムアウトは、次の方法でも制御されます。

* システムセキュリティ用の、個別の設定不可能な StorageGRID タイマー。デフォルトでは、各ユーザの認証トークンはユーザがサインインしてから 16 時間後に期限切れになります。ユーザの認証が期限切れになると、ブラウザの非アクティブタイムアウトが無効になっている場合やブラウザのタイムアウト値に達していない場合でも、そのユーザは自動的にサインアウトされます。トークンを更新するには、再度サインインする必要があります。
* アイデンティティプロバイダのタイムアウト設定（StorageGRID でシングルサインオン（SSO）が有効になっている場合）。
+
SSOが有効になっていて、ユーザのブラウザがタイムアウトした場合、StorageGRID に再度アクセスするには、SSOクレデンシャルを再入力する必要があります。を参照してください link:configuring-sso.html["シングルサインオンを設定します"]。



.手順
. * configuration *>* Security *>* Security settings *を選択します。
. [Browser inactivity timeout]*タブを選択します。
. [Sign out inactive users after *]フィールドに、ブラウザのタイムアウト時間を60秒から7日の間で指定します。
+
ブラウザのタイムアウト時間は、秒、分、時間、または日数で指定できます。

. [ 保存（ Save ） ] を選択します。ブラウザが一定期間非アクティブになっている場合、ユーザはGrid ManagerまたはTenant Managerからサインアウトされます。
+
新しい設定は、現在サインインしているユーザには影響しません。新しいタイムアウト設定を有効にするには、ユーザが再度サインインするか、ブラウザを更新する必要があります。


