---
permalink: admin/kms-viewing-encrypted-nodes.html 
sidebar: sidebar 
keywords: view encrypted nodes, kms nodes, appliances with kms 
summary: StorageGRID システムで、ノード暗号化設定が有効になっているアプライアンスノードに関する情報を表示できます。 
---
= 暗号化されたノードを表示する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システムでノード暗号化 * 設定が有効になっているアプライアンスノードに関する情報を表示できます。

.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key Management Server] ページが表示されます。Configuration Details タブには、設定済みのすべてのキー管理サーバが表示されます。

. ページの上部で、*[暗号化されたノード]*タブを選択します。
+
[Encrypted nodes]タブには、*[Node Encryption]*設定が有効になっているStorageGRID システム内のアプライアンスノードが表示されます。

. 各アプライアンスノードについて、表の情報を確認します。
+
[cols="1a,2a"]
|===
| 列（ Column ） | 説明 


 a| 
ノード名
 a| 
アプライアンスノードの名前。



 a| 
ノードタイプ
 a| 
ノードのタイプ。 Storage 、 Admin 、または Gateway 。



 a| 
サイト
 a| 
ノードがインストールされている StorageGRID サイトの名前。



 a| 
KMS名
 a| 
ノードに使用される KMS の説明的な名前。

KMSがリストされていない場合は、[Configuration details]タブを選択してKMSを追加します。

link:kms-adding.html["キー管理サーバ（ KMS ）を追加する"]



 a| 
キー UID
 a| 
アプライアンスノードでデータの暗号化と復号化に使用する暗号化キーの一意の ID 。キーUID全体を表示するには、セルの上にカーソルを置きます。

ダッシュ（ - - ）は、キー UID が不明であることを示します。アプライアンスノードと KMS 間の接続問題 が原因である可能性があります。



 a| 
ステータス
 a| 
KMS とアプライアンスノード間の接続のステータス。ノードが接続されている場合は、タイムスタンプが 30 分ごとに更新されます。KMS の設定変更後に接続ステータスが更新されるまで数分かかることがあります。

* 注： * 新しい値を表示するには、 Web ブラウザを更新する必要があります。

|===
. ステータス列に KMS 問題 と表示されている場合は、問題 にすぐに対処してください。
+
通常の KMS 操作中、ステータスは * KMS * に接続されます。ノードがグリッドから切断されると、ノードの接続状態が（意図的に停止しているか不明である）と表示されます。

+
その他のステータスメッセージは、同じ名前の StorageGRID アラートに対応します。

+
** KMS の設定をロードできませんでした
** KMS 接続エラー
** KMS 暗号化キー名が見つかりません
** KMS 暗号化キーのローテーションに失敗しました
** KMS キーでアプライアンスボリュームを復号化できませんでした
** KMS は設定されていません


+
これらのアラートに対して推奨される対処方法を実行します。




CAUTION: 問題が発生した場合は、データを完全に保護するために、すぐに対処する必要があります。
