---
permalink: admin/kms-viewing-details.html 
sidebar: sidebar 
keywords: view kms, view key management server 
summary: StorageGRID システム内の各キー管理サーバ（ KMS ）について、サーバ証明書とクライアント証明書の現在のステータスなどの情報を確認できます。 
---
= KMS の詳細を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID システム内の各キー管理サーバ（ KMS ）に関する情報を確認することができます。これには、サーバ証明書とクライアント証明書の現在のステータスも含まれます。

.手順
. 設定 * > * セキュリティ * > * キー管理サーバ * を選択します。
+
[Key management server]ページが表示されます。[設定の詳細]タブには、設定済みのキー管理サーバが表示されます。

. 各 KMS について、表の情報を確認します。
+
[cols="1a,2a"]
|===
| フィールド | 説明 


 a| 
KMS名
 a| 
KMS の説明的な名前。



 a| 
キー名
 a| 
KMS 内の StorageGRID クライアントのキーエイリアス。



 a| 
のキーを管理します
 a| 
KMS に関連付けられている StorageGRID サイト。

このフィールドには、特定の StorageGRID サイトの名前、または別の KMS （デフォルト KMS ）で管理されていないサイト * が表示されます



 a| 
ホスト名
 a| 
KMS の完全修飾ドメイン名または IP アドレス。

2 台のキー管理サーバからなるクラスタがある場合は、両方のサーバの完全修飾ドメイン名または IP アドレスが表示されます。クラスタに複数のキー管理サーバがある場合は、最初の KMS の完全修飾ドメイン名または IP アドレスと、クラスタ内の追加のキー管理サーバの数が表示されます。

例： `10.10.10.10 and 10.10.10.11` または `10.10.10.10 and 2 others`。

クラスタ内のすべてのホスト名を表示するには、KMSを開き、*[編集]*または*[アクション]*>*[編集]*を選択します。



 a| 
証明書の有効期限
 a| 
サーバ証明書、オプションの CA 証明書、およびクライアント証明書の現在の状態：有効、期限が切れている、期限が近づいている、または不明。

*注：*証明書の有効期限の更新を取得するには、StorageGRID が30分ほどかかる場合があります。現在の値を表示するには、 Web ブラウザの表示を更新する必要があります。

|===
. 証明書の有効期限が不明な場合は、30分ほど待ってからWebブラウザをリフレッシュしてください。
+

NOTE: KMSを追加した直後に、[Key Management Server]ページに証明書の有効期限が[Unknown]と表示されます。各証明書の実際のステータスの StorageGRID 取得には 30 分程度かかる場合があります。実際のステータスを確認するには、 Web ブラウザの表示を更新する必要があります。

. [証明書の有効期限]列に証明書の有効期限が切れているか、有効期限が近づいていることが示されている場合は、できるだけ早く問題 に対処してください。
+
「* kms CA certificate expiration *」、「* kms client certificate expiration *」、「* kms server certificate expiration *」の各アラートがトリガーされたら、各アラートの概要 をメモして推奨される対処方法を実行します。

+

CAUTION: データアクセスを維持するために、証明書の問題はできるだけ早く対処する必要があります。

. このKMSの証明書の詳細を表示するには、表からKMS名を選択します。
. KMSの概要ページで、サーバ証明書とクライアント証明書の両方のメタデータと証明書のPEMを確認します。必要に応じて、*[証明書の編集]*を選択して証明書を新しい証明書に置き換えます。

