---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。 
---
= 管理ノードとは
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ノードは、システムの設定、監視、ロギングなどの管理サービスを提供します。各グリッドにはプライマリ管理ノードが 1 つ必要で、冗長性を確保するために任意の数の非プライマリ管理ノードを設定できます。

Grid Manager または Tenant Manager にサインインすると、管理ノードに接続されます。どの管理ノードにも接続が可能で、各管理ノードに表示される StorageGRID システムのビューもほぼ同じです。ただし、メンテナンス手順はプライマリ管理ノードを使用して実行する必要があります。

管理ノードを使用して、 S3 および Swift クライアントトラフィックの負荷を分散することもできます。



== 優先送信者とは何ですか

StorageGRID 環境に複数の管理ノードが含まれている場合は、プライマリ管理ノードがアラート通知、AutoSupport メッセージ、SNMPトラップとインフォーム、および従来のアラーム通知の優先送信者となります。

通常のシステム運用では、優先送信者のみが通知を送信します。ただし、他のすべての管理ノードで優先送信者を監視します。問題が検出された場合、他の管理ノードは_standby senders_として動作します。

次の場合、複数の通知が送信されることがあります。

* 管理ノードどうしが「孤立」すると、優先送信者とスタンバイ送信者の両方が通知の送信を試み、通知のコピーが複数受信される可能性があります。
* スタンバイ送信者が優先送信者に関する問題を検出して通知の送信を開始すると、優先送信者は通知を再び送信できるようになることがあります。この場合、重複する通知が送信される可能性があります。優先送信者に関するエラーが検出されなくなると、スタンバイ送信者は通知の送信を停止します。
+

NOTE: AutoSupport メッセージのテスト時には、すべての管理ノードからテストEメールが送信されます。アラート通知をテストするときは、すべての管理ノードにサインインして接続を確認する必要があります。





== 管理ノードのプライマリサービス

次の表に、管理ノードのプライマリサービスを示します。ただし、この表にはすべてのノードサービスが表示されるわけではありません。

[cols="1a,2a"]
|===
| サービス | キー機能 


 a| 
Audit Management System （ AMS ）
 a| 
システムアクティビティとイベントを追跡します。



 a| 
Configuration Management Node （ CMN ）
 a| 
システム全体の設定を管理します。プライマリ管理ノードのみ



 a| 
管理アプリケーションプログラミングインターフェイス（ mgmt-api ）
 a| 
グリッド管理 API とテナント管理 API からの要求を処理します。



 a| 
高可用性
 a| 
管理ノードとゲートウェイノードのグループのハイアベイラビリティ仮想 IP アドレスを管理します。

* 注： * このサービスはゲートウェイノードにも搭載されています。



 a| 
ロードバランサ
 a| 
クライアントからストレージノードへの S3 および Swift トラフィックのロードバランシングを実現します。

* 注： * このサービスはゲートウェイノードにも搭載されています。



 a| 
ネットワーク管理システム（ NMS ）
 a| 
Grid Manager の機能を提供します。



 a| 
Prometheus
 a| 
すべてのノードのサービスから時系列の指標を収集して格納します。



 a| 
SSM （サーバステータスモニタ）
 a| 
オペレーティングシステムと基盤のハードウェアを監視します。

|===