---
permalink: s3/accessing-and-reviewing-audit-logs.html 
sidebar: sidebar 
keywords: access audit logs, review audit logs, view audit logs 
summary: 監査メッセージは StorageGRID サービスによって生成され、テキスト形式のログファイルに保存されます。監査ログの API 固有の監査メッセージにより、セキュリティ、運用、およびパフォーマンスについて、システムの健全性の評価に役立つ重要な監視データが提供されます。 
---
= 監査ログにアクセスして確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージは StorageGRID サービスによって生成され、テキスト形式のログファイルに保存されます。監査ログの API 固有の監査メッセージにより、セキュリティ、運用、およびパフォーマンスについて、システムの健全性の評価に役立つ重要な監視データが提供されます。

.作業を開始する前に
* 特定のアクセス権限が必要です。
* を使用することができます `Passwords.txt` ファイル。
* 管理ノードの IP アドレスを確認しておきます。


.このタスクについて
アクティブな監査ログファイルの名前はです `audit.log`をクリックし、を管理ノードに格納します。

1日に1回、アクティブなaudit.logファイルが保存され、新しいファイルが作成されます `audit.log` ファイルが開始されました。保存されたファイルの名前は、保存された日時をの形式で示しています `_yyyy-mm-dd.txt_`。

1日後、保存されたファイルは圧縮され、という形式で名前が変更されます `_yyyy-mm-dd.txt.gz_`元の日付を保持します。

この例は、アクティブを示しています `audit.log` ファイル。前日のファイルです (`2018-04-15.txt`）、および前日の圧縮ファイルです (`2018-04-14.txt.gz`）。

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----
.手順
. 管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 監査ログファイルが保存されているディレクトリに移動します。
+
`cd /var/local/audit/export`

. 必要に応じて、現在の監査ログファイルまたは保存された監査ログファイルを表示します。

