---
permalink: s3/configuring-security-for-rest-api.html 
sidebar: sidebar 
keywords: configure rest api security, TLS 
summary: REST API のセキュリティの実装を確認し、システムの保護方法について理解しておく必要があります。 
---
= REST API のセキュリティを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST API のセキュリティの実装を確認し、システムの保護方法について理解しておく必要があります。



== StorageGRID がREST APIのセキュリティを提供する仕組み

StorageGRID システムで REST API のセキュリティ、認証、および許可がどのように実装されるかを理解しておく必要があります。

StorageGRID では、次のセキュリティ対策が使用されます。

* ロードバランサエンドポイントで HTTPS が設定されている場合は、ロードバランササービスとのクライアント通信に HTTPS が使用されます。
+
ロードバランサエンドポイントを設定する際に、オプションで HTTP を有効にすることができます。たとえば、非本番環境でのテストなどに HTTP を使用できます。詳細については、 StorageGRID の管理手順を参照してください。

* StorageGRID は、ストレージノードとのクライアント通信にデフォルトでHTTPSを使用します。
+
これらの接続に対して HTTP を有効にすることもできます。たとえば、非本番環境でのテストなどに HTTP を使用できます。詳細については、 StorageGRID の管理手順を参照してください。

* StorageGRID とクライアント間の通信は、 TLS を使用して暗号化されます。
* ロードバランササービスとグリッド内のストレージノードの間の通信は、ロードバランサエンドポイントが HTTP と HTTPS どちらの接続を受け入れるように設定されているかに関係なく暗号化されます。
* REST API 処理を実行するには、クライアントが StorageGRID に HTTP 認証ヘッダーを提供する必要があります。




=== セキュリティ証明書とクライアントアプリケーション

クライアントは、ゲートウェイノードまたは管理ノード上のロードバランササービスに、ストレージノードに直接接続できます。

いずれの場合も、クライアントアプリケーションは、グリッド管理者がアップロードしたカスタムサーバ証明書または StorageGRID システムが生成した証明書を使用して、 TLS 接続を確立できます。

* ロードバランササービスに接続する場合、クライアントアプリケーションは、接続に使用するロードバランサエンドポイント用に設定された証明書を使用します。各エンドポイントには独自の証明書があり、グリッド管理者がアップロードしたカスタムサーバ証明書か、グリッド管理者がエンドポイントの設定時に StorageGRID で生成した証明書のいずれかです。
* クライアントアプリケーションは、ストレージノードに直接接続する場合、StorageGRID システムのインストール時にストレージノード用に生成されたシステム生成のサーバ証明書（システム認証局によって署名されたもの）を使用します。 または、グリッド管理者がグリッド用に提供した単一のカスタムサーバ証明書。


TLS 接続の確立に使用する証明書に署名した認証局を信頼するよう、クライアントを設定する必要があります。

ロードバランサエンドポイントの設定に関する情報や、ストレージノードへの直接TLS接続に使用する単一のカスタムサーバ証明書を追加する手順については、StorageGRID の管理手順を参照してください。



=== まとめ

次の表に、 S3 および Swift の REST API におけるセキュリティの問題に対する実装を示します。

[cols="2a,3a"]
|===
| Security 問題 の略 | REST API の実装 


 a| 
接続のセキュリティ
 a| 
TLS



 a| 
サーバ認証
 a| 
システム CA によって署名された X.509 サーバ証明書、または管理者から提供されたカスタムサーバ証明書



 a| 
クライアント認証
 a| 
* S3 ： S3 アカウント（アクセスキー ID とシークレットアクセスキー）
* Swift ： Swift アカウント（ユーザ名とパスワード）




 a| 
クライアント許可
 a| 
* S3 ：バケットの所有権と適用可能なすべてのアクセス制御ポリシー
* Swift ：管理者ロールのアクセス


|===
.関連情報
link:../admin/index.html["StorageGRID の管理"]



== TLS ライブラリのハッシュアルゴリズムと暗号化アルゴリズムがサポートされます

StorageGRID システムでは、クライアントアプリケーションが Transport Layer Security （ TLS ）セッションを確立する際に使用できる暗号スイートに制限があります。暗号を設定するには、*[設定]*>*[セキュリティ]*[セキュリティ設定]*に移動し、* TLSおよびSSHポリシー*を選択します。



=== サポートされる TLS のバージョン

StorageGRID では、 TLS 1.2 と TLS 1.3 がサポートされています。


IMPORTANT: SSLv3 と TLS 1.1 （またはそれ以前のバージョン）はサポートされなくなりました。

.関連情報
link:configuring-tenant-accounts-and-connections.html["テナントアカウントと接続を設定する"]
