---
permalink: s3/get-object.html 
sidebar: sidebar 
keywords: get object 
summary: S3 GET Object 要求を使用して、 S3 バケットからオブジェクトを読み出すことができます。 
---
= オブジェクトの取得
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 GET Object 要求を使用して、 S3 バケットからオブジェクトを読み出すことができます。



== オブジェクトとマルチパートオブジェクトを取得する

を使用できます `partNumber` マルチパートまたはセグメント化されたオブジェクトの特定の部分を読み出す要求パラメータ。。 `x-amz-mp-parts-count` response要素は、オブジェクトに含まれるパーツの数を示します。

設定できます `partNumber` セグメント化されたオブジェクト/マルチパートオブジェクトとセグメント化されていないオブジェクト/マルチパート以外のオブジェクトの場合は1。ただし、 `x-amz-mp-parts-count` 応答要素は、セグメント化されたオブジェクトまたはマルチパートオブジェクトの場合にのみ返されます。



== ユーザメタデータ内の UTF-8 文字

StorageGRID は、ユーザ定義メタデータ内のエスケープされた UTF-8 文字を解析も解釈もしません。ユーザ定義メタデータにエスケープされたUTF-8文字が含まれているオブジェクトに対するGET要求では、が返されません `x-amz-missing-meta` キーの名前または値に印刷できない文字が含まれている場合は、ヘッダーを指定します。



== サポートされない要求ヘッダーです

次の要求ヘッダーはサポートされていません `XNotImplemented`：

* `x-amz-website-redirect-location`




== バージョン管理

の場合 `versionId` サブリソースが指定されていません。バージョン管理されたバケット内のオブジェクトの最新バージョンが取得されます。オブジェクトの現在のバージョンが削除マーカーの場合は、「見つからない」ステータスがとともに返されます `x-amz-delete-marker` 応答ヘッダーをに設定しました `true`。



== ユーザ指定の暗号化キーによるサーバ側の暗号化（ SSE-C ）の要求ヘッダー

指定した一意のキーでオブジェクトが暗号化されている場合は、 3 つのヘッダーをすべて使用します。

* `x-amz-server-side-encryption-customer-algorithm`:指定します `AES256`。
* `x-amz-server-side-encryption-customer-key`:オブジェクトの暗号化キーを指定します
* `x-amz-server-side-encryption-customer-key-MD5`:オブジェクトの暗号化キーのMD5ダイジェストを指定します。



IMPORTANT: 指定した暗号化キーが格納されることはありません。暗号化キーを紛失すると、対応するオブジェクトが失われます。ユーザ指定のキーを使用してオブジェクトデータを保護する前に、の考慮事項を確認してください link:using-server-side-encryption.html["サーバ側の暗号化を使用します"]。



== クラウドストレージプールオブジェクトに対する GET Object の動作

オブジェクトがに格納されている場合 link:../ilm/what-cloud-storage-pool-is.html["クラウドストレージプール"]の場合、GET Object要求の動作はオブジェクトの状態によって異なります。を参照してください link:head-object.html["HEAD Object の実行"] 詳細：


NOTE: オブジェクトがクラウドストレージプールに格納され、かつそのオブジェクトのコピーがグリッドに 1 つ以上存在する場合、 GET Object 要求はクラウドストレージプールからデータを読み出す前に、グリッドからデータを読み出そうとします。

[cols="1a,1a"]
|===
| オブジェクトの状態 | GET Object の動作 


 a| 
StorageGRID に取り込まれているがまだ ILM によって評価されていないオブジェクト、または従来のストレージプールに格納されているオブジェクト、またはイレイジャーコーディングを使用しているオブジェクト
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。



 a| 
クラウドストレージプール内にあるが、まだ読み出し不可能な状態に移行していない
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。



 a| 
オブジェクトを読み出し不可能な状態に移行した
 a| 
`403 Forbidden`、 `InvalidObjectState`

を使用します link:post-object-restore.html["POST Object restore の実行"] 読み出し可能な状態へのオブジェクトのリストア要求。



 a| 
読み出し不可能な状態からリストア中である
 a| 
`403 Forbidden`、 `InvalidObjectState`

POST Object restore 要求が完了するまで待ちます。



 a| 
クラウドストレージプールへのリストアが完了している
 a| 
`200 OK`

オブジェクトのコピーが読み出されます。

|===


=== クラウドストレージプール内のマルチパートオブジェクトまたはセグメント化されたオブジェクト

マルチパートオブジェクトをアップロードした場合や StorageGRID が大きなオブジェクトをセグメントに分割した場合、 StorageGRID はオブジェクトのパーツまたはセグメントのサブセットをサンプリングすることでクラウドストレージプール内のオブジェクトが使用可能かどうかを判断します。GET Object要求が誤って返されることがあります `200 OK` オブジェクトの一部のパートがすでに読み出し不可能な状態に移行されている場合や、オブジェクトの一部のパートがまだリストアされていない場合。

このような場合は、次のよう

* GET Object 要求がデータの一部を返し、転送の途中で停止することがあります。
* 後続のGET Object要求が返されることがあります `403 Forbidden`。




== GET Objectとクロスグリッドレプリケーション

使用するポート link:../admin/grid-federation-overview.html["グリッドフェデレーション"] および link:../tenant/grid-federation-manage-cross-grid-replication.html["グリッド間レプリケーション"] バケットで有効になっている場合、S3クライアントはGET Object要求を発行してオブジェクトのレプリケーションステータスを確認できます。応答にはStorageGRID固有の情報が含まれます `x-ntap-sg-cgr-replication-status` 応答ヘッダー。次のいずれかの値が設定されます。

[cols="1a,2a"]
|===
| グリッド（ Grid ） | レプリケーションのステータス 


 a| 
ソース
 a| 
* *成功*：レプリケーションは成功しました。
* * pending*：オブジェクトはまだレプリケートされていません。
* *failure*:レプリケーションが永続的なエラーで失敗しました。ユーザーはエラーを解決する必要があります。




 a| 
宛先
 a| 
*replica*:オブジェクトはソースグリッドからレプリケートされました。

|===

NOTE: StorageGRID ではがサポートされません `x-amz-replication-status` ヘッダー。

.関連情報
link:s3-operations-tracked-in-audit-logs.html["監査ログで追跡される S3 処理"]
