---
permalink: s3/how-storagegrid-ilm-rules-manage-objects.html 
sidebar: sidebar 
keywords: ilm manage object rules 
summary: グリッド管理者が情報ライフサイクル管理（ ILM ）ルールを作成して、 S3 REST API クライアントアプリケーションから StorageGRID システムに取り込まれたオブジェクトデータを管理します。これらのルールは、以降のオブジェクトデータを格納する方法と場所を指定するために、 ILM ポリシーに追加されます。 
---
= StorageGRID の ILM ルールによるオブジェクトの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
グリッド管理者が情報ライフサイクル管理（ ILM ）ルールを作成して、 S3 REST API クライアントアプリケーションから StorageGRID システムに取り込まれたオブジェクトデータを管理します。これらのルールは、以降のオブジェクトデータを格納する方法と場所を指定するために、 ILM ポリシーに追加されます。

ILM の設定によって、オブジェクトの次の要素が決まります。

* * 地域 *
+
StorageGRID システム（ストレージプール）内またはクラウドストレージプール内のオブジェクトのデータの場所。

* * ストレージグレード *
+
フラッシュや回転式ディスクなど、オブジェクトデータの格納に使用されるストレージのタイプ。

* * 損失の保護 *
+
作成されるコピーの数と作成されるコピーのタイプ（レプリケーション、イレイジャーコーディング、またはその両方）。

* * 保持 *
+
オブジェクトのデータの管理方法、格納場所、損失からの保護方法の経過時間に応じて変更が加えられます。

* * 取り込み中の保護 *
+
取り込み時にオブジェクトデータを保護する方法。同期配置（取り込み動作に Balanced オプションまたは Strict オプションを使用）または中間コピー作成（ Dual commit オプションを使用）のいずれかです。



ILM ルールではオブジェクトをフィルタして選択できます。S3 を使用して取り込まれたオブジェクトは、 ILM ルールによって次のメタデータに基づいてフィルタできます。

* テナントアカウント
* バケット名
* 取り込み時間
* キーを押します
* 最終アクセス時間
+

NOTE: デフォルトでは、すべての S3 バケットで最終アクセス時間の更新が無効になっています。StorageGRID システムに[Last access time]オプションを使用するILMルールが含まれている場合は、そのルールで指定されたS3バケットに対して最終アクセス時間の更新を有効にする必要があります。Tenant ManagerでPUT Bucket last access time要求を使用します（を参照） link:../tenant/enabling-or-disabling-last-access-time-updates.html["最終アクセス日時の更新を有効または無効にします"]）をクリックするか、テナント管理APIを使用します。最終アクセス時間の更新を有効にする場合は、特に小さなオブジェクトを含むシステムで StorageGRID のパフォーマンスが低下する可能性があることに注意してください。

* 場所の制約
* オブジェクトのサイズ
* ユーザメタデータ
* オブジェクトタグ


.関連情報
link:../tenant/index.html["テナントアカウントを使用する"]

link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

link:put-bucket-last-access-time-request.html["PUT Bucket last access time のように指定します"]
