---
permalink: s3/operations-for-multipart-uploads.html 
sidebar: sidebar 
keywords: operations, multipart uploads, uploads, rest API 
summary: このセクションでは、 StorageGRID でのマルチパートアップロードの処理のサポートについて説明します。 
---
= マルチパートアップロードの処理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このセクションでは、 StorageGRID でのマルチパートアップロードの処理のサポートについて説明します。

マルチパートアップロードのすべての処理に、次の条件と注意事項が適用されます。

* 1 つのバケットに対して同時に実行するマルチパートアップロードが 1 、 000 件を超えないようにしてください。 1 、 000 件を超えると、そのバケットに対する List Multipart Uploads のクエリで完全な結果が返されないことがあります。
* StorageGRID は、マルチパートに AWS のサイズ制限を適用します。S3 クライアントは次のガイドラインに従う必要があります。
+
** マルチパートアップロードの各パートのサイズは 5MiB （ 5 、 242 、 880 バイト）と 5GiB （ 5 、 368 、 709 、 120 バイト）の間にする必要があります。
** 最後の部分は 5MiB （ 5,242,880 バイト）より小さくできます。
** 一般に、パーツサイズはできるだけ大きくする必要があります。たとえば、 100GiB オブジェクトの場合、 5GB のパートサイズを使用します。各パートは固有のオブジェクトとみなされるため、大きなパートサイズを使用するとStorageGRID メタデータのオーバーヘッドが削減されます。
** 5GB 未満のオブジェクトでは、マルチパートではないアップロードの使用を検討してください。


* ILMルールの取り込み動作がBalancedまたはStrictの場合は、マルチパートオブジェクトの各パートについて、ILMルールの取り込み動作がBalancedまたはStrictの場合はマルチパートアップロードの完了時にオブジェクト全体についてILMが評価されます。これがオブジェクトとパートの配置にどのように影響するかに注意する必要があります。
+
** S3 マルチパートアップロードの進行中に ILM が変更されると、マルチパートアップロードが完了した時点でオブジェクトの一部のパートが現在の ILM 要件を満たしていないことがあります。正しく配置されていないパートは ILM ルールによる再評価の対象としてキューに登録され、あとで正しい場所に移動されます。
** パートに対して ILM を評価する際、 StorageGRID はオブジェクトのサイズではなくパートのサイズでフィルタリングします。つまり、オブジェクト全体のILM要件を満たしていない場所にオブジェクトの一部を格納できます。たとえば、 10GB 以上のオブジェクトをすべて DC1 に格納し、それより小さいオブジェクトをすべて DC2 に格納するルールの場合、 10 パートからなるマルチパートアップロードの 1GB の各パートは取り込み時に DC2 に格納されます。オブジェクト全体に対して ILM が評価されると、オブジェクトのすべてのパートが DC1 に移動されます。


* マルチパートアップロードでは、すべての処理で StorageGRID の整合性制御がサポートされます。
* マルチパートアップロードでは、必要に応じてサーバ側の暗号化を使用できます。SSE（StorageGRIDで管理されるキーによるサーバ側の暗号化）を使用するには、を指定します `x-amz-server-side-encryption` Initiate Multipart Upload要求のみの要求ヘッダー。SSE-C （ユーザ指定のキーによるサーバ側の暗号化）を使用する場合は、 Initiate Multipart Upload 要求と後続の各 Upload Part 要求に、同じ 3 つの暗号化キー要求ヘッダーを指定します。


[cols="2a,3a"]
|===
| 操作 | 実装 


 a| 
マルチパートアップロードをリストします
 a| 
を参照してください link:list-multipart-uploads.html["マルチパートアップロードをリストします"]



 a| 
マルチパートアップロードを開始します
 a| 
を参照してください link:initiate-multipart-upload.html["マルチパートアップロードを開始します"]



 a| 
パーツをアップロードします
 a| 
を参照してください link:upload-part.html["パーツをアップロードします"]



 a| 
パーツのアップロード - コピー
 a| 
を参照してください link:upload-part-copy.html["パーツのアップロード - コピー"]



 a| 
Complete Multipart Upload の実行
 a| 
を参照してください link:complete-multipart-upload.html["Complete Multipart Upload の実行"]



 a| 
マルチパートアップロードを中止します
 a| 
Amazon S3 REST API のすべての動作が実装されています。予告なく変更される場合があります。



 a| 
パーツをリストします
 a| 
Amazon S3 REST API のすべての動作が実装されています。予告なく変更される場合があります。

|===
.関連情報
* link:consistency-controls.html["整合性制御"]
* link:using-server-side-encryption.html["サーバ側の暗号化を使用します"]

