---
permalink: monitor/configure-audit-messages.html 
sidebar: sidebar 
keywords: audit messages, configure syslog server, configure external syslog server. log destinations 
summary: すべての StorageGRID ノードで監査メッセージが生成され、システムアクティビティとイベントが追跡されます。監査レベルを調整して、記録する監査メッセージの種類や数を増減できます。 
---
= 監査メッセージとログの送信先を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査メッセージとログには、システムのアクティビティとセキュリティイベントが記録され、監視とトラブルシューティングに不可欠なツールです。監査レベルを調整して、記録する監査メッセージの種類や数を増減できます。必要に応じて、クライアントの読み取りおよび書き込み監査メッセージに含める HTTP 要求ヘッダーを定義できます。また、外部 syslog サーバを設定したり、監査情報のデスティネーションを変更したりすることもできます。

監査メッセージの詳細については、を参照してください link:../audit/index.html["監査ログを確認します"]。

.作業を開始する前に
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* Maintenance または Root アクセス権限が必要です。


.このタスクについて
すべての StorageGRID ノードで監査メッセージとログが生成され、システムアクティビティとイベントが追跡されます。デフォルトでは、監査情報は管理ノードの監査ログに送信されます。監査レベルを調整して、監査ログに記録する監査メッセージの種類や数を増減できます。必要に応じて、監査情報を手動で収集するために元のノードに一時的に格納するように設定できます。


IMPORTANT: 大規模なグリッドを使用する場合、複数のタイプのS3アプリケーションを使用する場合、またはすべての監査データを保持する場合は、外部のsyslogサーバを設定し、監査情報をリモートで保存します。外部サーバを使用すると、監査データの完全性を損なうことなく、監査メッセージロギングによるパフォーマンスへの影響を最小限に抑えることができます。を参照してください link:../monitor/considerations-for-external-syslog-server.html["外部 syslog サーバに関する考慮事項"] を参照してください。



== 監査ログの監査メッセージレベルを変更します

監査ログでは、次のカテゴリのメッセージごとに異なる監査レベルを設定できます。

[cols="1a,3a"]
|===
| 監査カテゴリ | 説明 


 a| 
システム
 a| 
デフォルトでは、このレベルは Normal に設定されます。を参照してください link:../audit/system-audit-messages.html["システム監査メッセージ"]。



 a| 
ストレージ
 a| 
デフォルトでは、このレベルは Error に設定されています。を参照してください link:../audit/object-storage-audit-messages.html["オブジェクトストレージ監査メッセージ"]。



 a| 
管理
 a| 
デフォルトでは、このレベルは Normal に設定されます。を参照してください link:../audit/management-audit-message.html["管理監査メッセージ"]。



 a| 
クライアント読み取り
 a| 
デフォルトでは、このレベルは Normal に設定されます。を参照してください link:../audit/client-read-audit-messages.html["クライアント読み取り監査メッセージ"]。



 a| 
クライアントからの書き込み
 a| 
デフォルトでは、このレベルは Normal に設定されます。を参照してください link:../audit/client-write-audit-messages.html["クライアント書き込み監査メッセージ"]。



 a| 
ILM処理
 a| 
デフォルトでは、このレベルは Normal に設定されます。を参照してください link:../audit/ilm-audit-messages.html["ILM処理の監査メッセージ"]。

|===

NOTE: これらのデフォルト値は、 StorageGRID 10.3 以降を最初にインストールした場合に適用されます。以前のバージョンの StorageGRID からアップグレードした場合、すべてのカテゴリのデフォルトは Normal に設定されます。


NOTE: アップグレード中は、監査レベルの設定はすぐには有効になりません。

.手順
. * configuration * > * Monitoring * > * Audit and syslog server * を選択します。
. 監査メッセージのカテゴリごとに、ドロップダウンリストから監査レベルを選択します。
+
[cols="1a,3a"]
|===
| 監査レベル | 説明 


 a| 
オフ
 a| 
このカテゴリの監査メッセージはログに記録されません。



 a| 
エラー
 a| 
エラーメッセージのみがログに記録されます -- 結果コードが「成功」（ SUCS ）以外の監査メッセージ。



 a| 
正常
 a| 
標準のトランザクション・メッセージはログに記録されますこのメッセージは ' カテゴリに関する次の手順に記載されています



 a| 
デバッグ
 a| 
非推奨。このレベルの動作は Normal 監査レベルと同じです。

|===
+
特定のレベルに含まれるメッセージには、上位レベルでロギングされるメッセージも含まれます。たとえば、 Normal レベルには Error レベルのメッセージがすべて含まれます。

+

NOTE: S3アプリケーションに対するクライアント読み取り処理の詳細なレコードを確認する必要がない場合は、必要に応じて* Client Reads *設定を* Error *に変更して、監査ログに記録される監査メッセージの数を減らします。

. 必要に応じて、 * Audit protocol headers * で、クライアントの読み取りおよび書き込み監査メッセージに含める HTTP 要求ヘッダーを定義します。0 個以上の文字に一致させるには、ワイルドカードとしてアスタリスク（ \* ）を使用します。リテラルアスタリスクに一致させるには、エスケープシーケンス（ \ * ）を使用します。
+

NOTE: 監査プロトコルヘッダーは、 S3 要求と Swift 要求にのみ適用されます。

. 必要に応じて、「 * 別のヘッダーを追加」を選択して追加のヘッダーを作成します。
+
要求に HTTP ヘッダーが含まれている場合、 HTTP ヘッダーは HTRH フィールドの下の監査メッセージに含まれます。

+

NOTE: 監査プロトコル要求ヘッダーは、 * クライアント読み取り * または * クライアント書き込み * の監査レベルが * オフ * でない場合にのみ記録されます。

. [ 保存（ Save ） ] を選択します
+
設定が正常に保存されたことを示す緑のバナーが表示されます。





== 外部 syslog サーバを使用します

監査情報をリモートで保存する場合は、外部 syslog サーバを設定できます。

* 外部の syslog サーバに監査情報を保存する場合は、に進みます link:../monitor/configuring-syslog-server.html["外部 syslog サーバを設定します"]。
* 外部syslogサーバを使用しない場合は、に進みます <<Select-audit-information-destinations,監査情報の送信先を選択します>>。




== 監査情報の送信先を選択します

監査ログ、セキュリティイベントログ、およびアプリケーションログの送信先を指定できます。


NOTE: 一部の送信先は、外部 syslog サーバを使用している場合にのみ指定できます。を参照してください link:../monitor/configuring-syslog-server.html["外部 syslog サーバを設定します"] 外部 syslog サーバを設定します。


NOTE: StorageGRID ソフトウェアログの詳細については、を参照してください link:../monitor/storagegrid-software-logs.html#["StorageGRID ソフトウェアのログ"]。

. Audit and syslog server ページで、表示されたオプションから監査情報の宛先を選択します。
+
[cols="1a,2a"]
|===
| オプション | 説明 


 a| 
デフォルト（管理ノード / ローカルノード）
 a| 
監査メッセージが監査ログに送信されます (`audit.log`管理ノードでは、セキュリティイベントログとアプリケーションログが生成されたノード（「ローカルノード」とも呼ばれます）に格納されます。



 a| 
外部 syslog サーバ
 a| 
監査情報が外部 syslog サーバに送信され、ローカルノードに保存されます。送信される情報の種類は、外部 syslog サーバの設定方法によって異なります。このオプションは、外部 syslog サーバを設定した場合にのみ有効になります。



 a| 
管理ノードと外部 syslog サーバ
 a| 
監査メッセージが監査ログに送信されます (`audit.log`）が管理ノードに送信され、監査情報が外部syslogサーバに送信されてローカルノードに保存されます。送信される情報の種類は、外部 syslog サーバの設定方法によって異なります。このオプションは、外部 syslog サーバを設定した場合にのみ有効になります。



 a| 
ローカルノードのみ
 a| 
管理ノードまたはリモート syslog サーバには監査情報は送信されません。監査情報は、生成したノードにのみ保存されます。

* 注： StorageGRID は、定期的にこれらのローカルログをローテーションから削除して、スペースを解放します。ノードのログファイルが 1GB に達すると、既存のファイルが保存され、新しいログファイルが開始されます。ログのローテーションの上限は 21 ファイルです。ログファイルの 22 番目のバージョンが作成されると、最も古いログファイルが削除されます。各ノードには平均約 20GB のログデータが格納されます。

|===
+

NOTE: すべてのローカルノードで生成された監査情報はに格納されます `/var/local/log/localaudit.log`

. [ 保存（ Save ） ] を選択します。
+
警告メッセージが表示されます。

. [OK]*を選択して、監査情報の保存先を変更することを確認します。
+
監査設定が保存されたことを示す緑色のバナーが表示されます。

+
選択した送信先に新しいログが送信されます。既存のログは現在の場所に残ります。



.関連情報
link:../monitor/considerations-for-external-syslog-server.html["外部 syslog サーバに関する考慮事項"]

link:../admin/index.html["StorageGRID の管理"]

link:../troubleshoot/troubleshooting-syslog-server.html["外部 syslog サーバのトラブルシューティングを行います"]
