---
permalink: sg6100/shut-down-sgf6112.html 
sidebar: sidebar 
keywords: storagegrid, sgf6112, power off, turn off, shut off, shutdown, shut down, 
summary: ハードウェアのメンテナンスを実行するには、アプライアンスをシャットダウンします。 
---
= SGF6112アプライアンスをシャットダウンします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアのメンテナンスを実行するには、アプライアンスをシャットダウンします。

.作業を開始する前に
* これで完了です link:locating-sgf6112-in-data-center.html["アプライアンスを物理的に設置します"]。


.このタスクについて
サービスの中断を防ぐには、通常サービスの中断が予想される時間帯に、スケジュールされたメンテナンス時間中にアプライアンスをシャットダウンしてください。

.手順
. アプライアンスをシャットダウンします。
+

CAUTION: 次のコマンドを入力して、アプライアンスの制御シャットダウンを実行する必要があります。不要なアラートを回避し、フルログを利用できることを確認し、サービスの停止を回避するために、可能なかぎり通常の方法でシャットダウンすることを推奨します。

+
.. グリッドノードにまだログインしていない場合は、PuTTYまたは別のsshクライアントを使用してログインします。
+
... 次のコマンドを入力します。 `ssh admin@_grid_node_IP_`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
... 次のコマンドを入力してrootに切り替えます。 `su -`
... に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



.. アプライアンスをシャットダウンします。+
`*shutdown -h now*`
+
このコマンドの実行には 10 分程度かかる場合があります。



. 次のいずれかの方法で、アプライアンスの電源がオフになっていることを確認します。
+
** アプライアンス前面の電源 LED を調べて、消灯していることを確認します。
** BMC インターフェイスの電源制御ページで、アプライアンスがオフになっていることを確認します。



