---
permalink: maintain/considerations-for-decommissioning-grid-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: この手順 を開始して 1 つ以上のノードの運用を停止する前に、各タイプのノードが削除された場合の影響を理解しておく必要があります。ノードの運用が正常に停止されると、ノードのサービスが無効になり、ノードが自動的にシャットダウンされます。 
---
= グリッドノードの運用停止に関する一般的な考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順 を開始して 1 つ以上のノードの運用を停止する前に、各タイプのノードが削除された場合の影響を理解しておく必要があります。ノードの運用が正常に停止されると、ノードのサービスが無効になり、ノードが自動的にシャットダウンされます。

ノードの運用を停止するとStorageGRID が無効な状態になる場合は、運用を停止できません。次のルールが適用されます。

* プライマリ管理ノードは運用停止できません。
* アーカイブノードは運用停止できません。
* いずれかのネットワークインターフェイスがハイアベイラビリティ（HA）グループに属している管理ノードまたはゲートウェイノードの運用を停止することはできません。
* 削除するとADCクォーラムに影響するストレージノードの運用を停止することはできません。
* アクティブなILMポリシーに必要なストレージノードは運用停止できません。
* 1 つのノードの運用停止手順 では、 10 個を超えるストレージノードの運用を停止しないでください。
* グリッドに切断されているノード（[Health]が[Unknown]または[Administratively Down]のノード）が含まれている場合は、接続されているノードの運用を停止できません。切断されているノードは、運用停止するかリカバリしておく必要があります。
* グリッド内に切断されているノードが複数ある場合は、それらのノードをすべて同時に運用停止する必要があるため、予期しない結果になる可能性があります。
* 切断されているノードを削除できない場合（ADCクォーラムに必要なストレージノードなど）は、切断されている他のノードを削除できません。
* 古いアプライアンスを新しいアプライアンスに交換する場合は、を検討してください link:../commonhardware/how-appliance-node-cloning-works.html["アプライアンスノードのクローニング"] 古いノードの運用を停止して新しいノードを追加する代わりに、拡張を行います。



IMPORTANT: 運用停止手順で指示されるまでは、グリッドノードの仮想マシンやその他のリソースを削除しないでください。
