---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: ストレージノードの運用を停止する際には、 StorageGRID がそのノードのオブジェクトデータとメタデータをどのように管理しているかを理解しておく必要があります。 
---
= ストレージノードの運用停止に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの運用を停止する際には、 StorageGRID がそのノードのオブジェクトデータとメタデータをどのように管理しているかを理解しておく必要があります。

ストレージノードの運用停止には、次の考慮事項と制限事項が適用されます。

* ADC クォーラムやアクティブな ILM ポリシーなどの運用要件を満たす十分な数のストレージノードが常にシステムに存在している必要があります。この要件を満たすために、拡張処理で新しいストレージノードを追加してから既存のストレージノードの運用を停止することが必要になる場合があります。
* 運用を停止する際に対象のストレージノードが切断されていると、システムは接続されているストレージノードのデータを使用してデータを再構築する必要があり、その結果、データが失われる可能性があります。
* ストレージノードを削除する場合、大量のオブジェクトデータをネットワーク経由で転送する必要があります。この転送が通常のシステム処理に影響することはありませんが、 StorageGRID システムが消費するネットワーク帯域幅の総量に影響する可能性があります。
* ストレージノードの運用停止に関連するタスクは、通常のシステム処理に関連するタスクよりも優先度が低くなっています。つまり、運用停止処理が StorageGRID の通常のシステム処理を妨げることはなく、システムがアクティブでない期間に運用停止処理をスケジュールする必要もありません。運用停止処理はバックグラウンドで実行されるため、プロセスの所要時間を見積もることは困難です。一般に、システムがビジー状態でないとき、または一度に 1 つのストレージノードのみを削除するときは、運用停止処理が迅速に終了します。
* ストレージノードの運用停止には、数日から数週間かかることがあります。それに応じてこの手順 を計画してください運用停止プロセスはシステム処理に影響しないように設計されていますが、他の手順が制限される可能性があります。一般に、システムのアップグレードや拡張を計画している場合は、グリッドノードを削除する前に実行する必要があります。
* 必要に応じて、ストレージノードが関係する運用停止手順を特定の段階で一時停止して他のメンテナンス手順を実行し、その完了後に運用停止手順を再開できます。
* 運用停止タスクの実行中は、どのグリッドノードでもデータ修復処理を実行できません。
* ストレージノードの運用停止中は、 ILM ポリシーに変更を加えないでください。
* ストレージノードを削除すると、そのノードのデータは他のグリッドノードに移行されます。ただし、このデータは運用停止されたグリッドノードから完全には削除されません。完全かつ安全にデータを削除するには、運用停止手順 の完了後に、運用停止したグリッドノードのドライブを消去する必要があります。
* ストレージノードの運用を停止すると、次のアラートとアラームが生成され、関連する E メール通知および SNMP 通知が送信される可能性があります。
+
** * ノードと通信できません * アラート。このアラートは、 ADC サービスが含まれるストレージノードの運用を停止した場合にトリガーされます。このアラートは、運用停止処理が完了すると解決します。
** VSTU （ Object Verification Status ）アラーム。このアラームは Notice レベルで、運用停止プロセスでストレージノードがメンテナンスモードに移行していることを示しています。
** Casa （ Data Store Status ）アラーム。このアラームは Major レベルで、サービスが停止したために Cassandra データベースが停止することを示しています。




.関連情報
link:restoring-object-data-to-storage-volume.html["オブジェクトデータをストレージボリュームにリストア"]
