---
permalink: maintain/decommissioning-disconnected-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, connected nodes, decommission node, storage node, disconnected storage node 
summary: 切断されているストレージノードの運用を停止した場合にどうなるかを理解しておく必要があります（ヘルスが「 Unknown 」または「 Administratively Down 」）。 
---
= 切断されているストレージノードの運用を停止
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
切断されているストレージノードの運用を停止した場合（ヘルスが「 Unknown 」または「 Administratively Down 」）は、どうなるかを理解しておく必要があります。

グリッドから切断されているストレージノードの運用を停止すると、 StorageGRID は他のストレージノードのデータを使用して、切断されているノード上にあったオブジェクトデータとメタデータを再構築します。この処理は、運用停止手順の最後にデータ修復ジョブを自動的に開始することで行われます。

切断されているストレージノードの運用を停止する前に、次の点を確認してください。

* 切断されているノードの運用停止は、オンラインにしたりリカバリしたりできないことが確実である場合を除き、絶対に実行しないでください。
+

IMPORTANT: ノードからオブジェクトデータをリカバリできる可能性がある場合は、この手順 を実行しないでください。代わりに、テクニカルサポートに問い合わせて、ノードのリカバリが可能かどうかを確認してください。

* 切断されているストレージノードに特定のオブジェクトの唯一のコピーが含まれている場合、ノードの運用を停止するとそのオブジェクトは失われます。データ修復ジョブは、現在接続されているストレージノードに、 1 つ以上のレプリケートコピーまたは十分なイレイジャーコーディングフラグメントが含まれている場合のみ、オブジェクトを再構築してリカバリできます。
* 切断されているストレージノードの運用を停止する場合、手順 の運用停止は比較的短時間で完了します。ただし、データ修復ジョブは実行に数日から数週間かかることがあり、運用停止手順 によって監視されません。これらのジョブは手動で監視し、必要に応じて再開してください。を参照してください link:checking-data-repair-jobs.html["データ修復ジョブを確認します"]。
* 切断されている複数のストレージノードを一度に運用停止すると、データが失われる可能性があります。利用可能な状態で残るオブジェクトデータ、メタデータ、またはイレイジャーコーディングフラグメントのコピーが少なすぎると、システムがデータを再構築できない場合があります。
+

IMPORTANT: 切断されていてリカバリできないストレージノードが複数ある場合は、テクニカルサポートに連絡して、最適な対処方法を確認してください。


