---
permalink: maintain/index.html 
sidebar: sidebar 
keywords: maintain overview, maintenance overview, about maintain, about maintenance 
summary: 以下の手順を使用して、 StorageGRID システムを保守し、障害からリカバリします。 
---
= リカバリとメンテナンス：概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下の手順を使用して、 StorageGRID システムを保守し、障害からリカバリします。



== これらの手順について

ここでは、ソフトウェアホットフィックスの適用、グリッドノードのリカバリ、障害が発生したサイトのリカバリ、グリッドノードまたはサイト全体の運用停止、ネットワークのメンテナンス、ホストレベルおよびミドルウェアのメンテナンス手順の実行、およびグリッドノードの作業手順の実行方法について説明します。


NOTE: これらの説明では、「 Linux 」とは Red Hat ® Enterprise Linux ® 、 Ubuntu ® 、 CentOS 、または Debian ® の環境を指します。を使用します https://["NetApp Interoperability Matrix Tool で確認できます"^] をクリックすると、サポートされるバージョンのリストが表示されます。



== 作業を開始する前に

* StorageGRID システムを幅広く理解している。
* StorageGRID システムのトポロジを確認し、グリッドの設定を把握しておきます。
* すべての指示に厳密に従い、すべての警告に注意する必要があります。
* ここで説明していないメンテナンス手順がサポートされていないか、サービス契約が必要であることを理解しておきます。




== アプライアンスのメンテナンス手順

ハードウェアの手順については、StorageGRID アプライアンスのメンテナンス手順を参照してください。

* link:../sg6100/index.html["SGF6112アプライアンスのメンテナンス"]
* link:../sg100-1000/index.html["SG100およびSG1000アプライアンスのメンテナンス"]
* link:../sg6000/index.html["SG6000 アプライアンスをメンテナンスする"]
* link:../sg5700/index.html["SG5700 アプライアンスをメンテナンスする"]

