---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: ストレージノードの運用を停止する場合は、運用停止プロセスを開始する前に、 StorageGRID システムの ILM ポリシーを確認してください。 
---
= ILM ポリシーとストレージ構成を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードの運用を停止する場合は、運用停止プロセスを開始する前に StorageGRID システムの ILM ポリシーを確認してください。

運用停止時に、運用停止されたストレージノードのすべてのオブジェクトデータが他のストレージノードに移行されます。


NOTE: 運用停止中の ILM ポリシーは、運用停止後のポリシーとして使用されます。運用停止を開始する前と運用停止の完了後に、このポリシーがデータの要件を満たしていることを確認する必要があります。

StorageGRID システムがストレージノードの運用停止に対応するために適切な場所に適切なタイプの容量を引き続き十分に確保できるように、アクティブな ILM ポリシーのルールを確認する必要があります。

次の点を考慮してください。

* ILM 評価サービスで ILM ルールを満たすようにオブジェクトデータをコピーすることは可能か。
* 運用停止処理の進行中にサイトが一時的に使用不能になった場合は、どうなりますか？追加のコピーを別の場所に作成できるか。
* 運用停止プロセスは、コンテンツの最終的な配信にどのように影響しますか。を参照してください link:consolidating-storage-nodes.html["ストレージノードを統合します"]では、古いストレージノードの運用を停止する前に新しいストレージノードを追加してください。小さいストレージノードの運用を停止してから、交換用に大きいストレージノードを追加すると、以前からあるストレージノードが容量の限界に近づき、新しいストレージノードにはほとんどコンテンツが存在しない状態になる可能性があります。新しいオブジェクトデータの書き込み処理のほとんどは新しいストレージノードに送信されるため、システム処理の全体的な効率が低下します。
* アクティブな ILM ポリシーを満たす十分な数のストレージノードが常にシステムに存在しているか。
+

NOTE: ILMポリシーを満たすことができないと、バックログやアラームが発生し、StorageGRID システムの運用が停止する可能性があります。



次の表に示す要素を評価して、運用停止プロセスによって実現する推奨トポロジが ILM ポリシーを満たすことを確認します。

[cols="1a,2a"]
|===
| 評価する領域 | 注： 


 a| 
使用可能容量
 a| 
StorageGRID システムに格納されているすべてのオブジェクトデータに対応できるだけの十分なストレージ容量があるか。 運用停止が必要なストレージノードに現在格納されているオブジェクトデータの永続的なコピーを含めるかどうか。運用停止処理が完了してから妥当な期間、格納されるオブジェクトデータについて予測される増加に対応できるだけの十分な容量があるか。



 a| 
ストレージの場所
 a| 
StorageGRID システム全体に十分な容量が残っている場合、 StorageGRID システムのビジネスルールを満たす適切な場所に容量が配置されているか。



 a| 
ストレージタイプ
 a| 
運用停止処理が完了したあとに、適切なタイプのストレージを十分に確保できるか。たとえば、コンテンツをその保管期間に応じて特定のタイプのストレージから別のタイプのストレージに移動するように ILM ルールで指示される場合があります。その場合は、 StorageGRID システムの最終的な構成に、適切なタイプのストレージが十分に確保されていることを確認する必要があります。

|===
.関連情報
link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]

link:../expand/index.html["グリッドを展開します"]
