---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: ストレージノードを追加したら、ECのリバランシング手順 を使用して、既存および新規のストレージノードにイレイジャーコーディングフラグメントを再配置できます。 
---
= ストレージノードの追加後にイレイジャーコーディングデータをリバランシングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージノードを追加したら、ECのリバランシング手順 を使用して、既存および新規のストレージノードにイレイジャーコーディングフラグメントを再配置できます。

.作業を開始する前に
* 新しいストレージノードを追加する拡張手順が完了している。
* を確認しておきます link:considerations-for-rebalancing-erasure-coded-data.html["イレイジャーコーディングデータのリバランシングに関する考慮事項"]。
* レプリケートされたオブジェクトデータがこの手順 によって移動されることはなく、イレイジャーコーディングデータの移動先を特定する際に、 EC 手順 が各ストレージノードでレプリケートされたデータの使用量を考慮しないことを理解しておきます。
* を使用することができます `Passwords.txt` ファイル。


.この手順 が実行されたときの動作
手順 を起動する前に、次の点に注意してください。

* 1つ以上のボリュームがオフラインの（アンマウントされた）場合、またはオンラインの（マウントされた）ボリュームがエラー状態の場合、ECリバランシング手順 は開始されません。
* EC のリバランシングによって、手順 が一時的に大量のストレージをリザーブします。ストレージアラートがトリガーされる場合がありますが、リバランシングが完了すると解決します。予約に十分なストレージがない場合、 EC のリバランシング手順 は失敗します。ストレージ予約は、手順 が失敗したか成功したかに関係なく、 EC のリバランシング手順 が完了したときに解放されます。
* ECのリバランシングの処理中にボリュームがオフラインになったりエラーが発生したりすると、リバランシングプロセスは部分的に完了し、データが失われることはありません。すべてのボリュームがエラーなしでオンラインになった時点で、ECリバランシング手順 を再開できます。
* ECリバランシング手順 の実行中は、ILM処理、S3およびSwiftクライアント処理のパフォーマンスに影響する可能性があります。
+

NOTE: オブジェクト（またはオブジェクトパーツ）をアップロードするために S3 および Swift API 処理を実行すると、 EC のリバランシング中に 24 時間以上かかる場合に手順 のリバランシングが失敗することがあります。該当するILMルールで取り込み時にBalanced配置またはStrict配置が使用されている場合、長時間のPUT処理は失敗します。次のエラーが報告されます。 `500 Internal Server Error`。



.手順
. [[review_object_storage] ] リバランシングするサイトの現在のオブジェクトストレージの詳細を確認します。
+
.. [* nodes （ノード） ] を選択します
.. サイトで最初のストレージノードを選択します。
.. [ * ストレージ * ] タブを選択します。
.. [Storage Used - Object Data]グラフにカーソルを合わせ、ストレージノード上のレプリケートデータとイレイジャーコーディングデータの現在の量を確認します。
.. 同じ手順を繰り返して、サイトの他のストレージノードを表示します。


. プライマリ管理ノードにログインします。
+
.. 次のコマンドを入力します。 `ssh admin@_primary_Admin_Node_IP_`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
.. 次のコマンドを入力してrootに切り替えます。 `su -`
.. に記載されているパスワードを入力します `Passwords.txt` ファイル。
+
rootとしてログインすると、プロンプトがから変わります `$` 終了： `#`。



. 手順 を起動します。
+
`rebalance-data start --site "_site-name_"`

+
の場合 `"_site-name_"`をクリックし、新しいストレージノードを追加した最初のサイトを指定します。囲みます `site-name` 引用符で囲みます。

+
EC Rebalance 手順 が開始され、ジョブ ID が返されます。

. ジョブ ID をコピーします。
. EC Rebalance 手順 のステータスを監視します。
+
** 単一の EC Rebalance 手順 のステータスを表示するには、次の手順を実行します
+
`rebalance-data status --job-id _job-id_`

+
の場合 `_job-id_`で、手順 の起動時に返されたIDを指定します。

** 現在の EC Rebalance 手順 と、以前に完了した手順のステータスを表示するには、次の手順を実行します。
+
`rebalance-data status`

+
[NOTE]
====
rebalance -dataコマンド のヘルプを表示するには、次の手順を実行します。

`rebalance-data --help`

====


. 返されたステータスに基づいて、追加の手順を実行します。
+
** ステータスがの場合 `In progress`を実行している場合、ECのリバランシング処理はまだ実行中です。手順 は、完了するまで定期的に監視する必要があります。
+
現在のジョブの推定完了時間と完了率を表示するには、次の手順を実行します。

+
... [*support*>] 、 [*Tools] 、 [*Metrics] の順に選択します。
... [Grafana]セクションで[EC Overview]*を選択します。
... グリッド EC ジョブの完了予想時間 * ダッシュボードと * グリッド EC ジョブの完了率 * ダッシュボードを確認します。


** ステータスがの場合 `Success`必要に応じて <<review_object_storage,オブジェクトストレージを確認する>> をクリックすると、サイトの最新の詳細が表示されます。
+
イレイジャーコーディングされたデータをサイトのストレージノード間でより均等に配置します。

+
[TIP]
====
次のメッセージが表示された場合は、すべてのイレイジャーコーディングデータのリバランシングが完了するまでEC rebalance手順 を再度実行します。

`The moves in this rebalance job have been limited. To rebalance additional data, start EC rebalance again for the same site.`

====
** ステータスがの場合 `Failure`：
+
... サイトのすべてのストレージノードがグリッドに接続されていることを確認します。
... これらのストレージノードに影響している可能性があるアラートがないかどうかを確認し、解決してください。
... ECリバランシング手順 を再起動します。
+
`rebalance-data start –-job-id _job-id_`

... ECのリバランシング手順 のステータスがまだの場合 `Failure`、テクニカルサポートにお問い合わせください。




. EC Rebalance 手順 によって大量の負荷が生成されている（取り込み処理に影響があるなど）場合は、手順 を一時停止します。
+
`rebalance-data pause --job-id _job-id_`

. EC のリバランシング手順 を終了する必要がある場合（ StorageGRID ソフトウェアのアップグレードを実行できるようにする場合など）は、次のように入力します。
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: EC のリバランシング手順 を終了すると、移動済みのデータフラグメントは新しい場所に残ります。データは元の場所に戻されません。

. 複数のサイトでイレイジャーコーディングを使用している場合は、影響を受ける他のすべてのサイトに対してこの手順 を実行します。

