---
permalink: ilm/enabling-s3-object-lock-globally.html 
sidebar: sidebar 
keywords: enable s3 object lock, object lock 
summary: オブジェクトデータの保存時に S3 テナントアカウントが規制要件に準拠する必要がある場合は、 StorageGRID システム全体で S3 オブジェクトのロックを有効にする必要があります。グローバルな S3 オブジェクトのロック設定を有効にすると、 S3 テナントユーザは S3 オブジェクトのロックでバケットとオブジェクトを作成および管理できるようになります。 
---
= S3 オブジェクトのロックをグローバルに有効にします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
オブジェクトデータの保存時に S3 テナントアカウントが規制要件に準拠する必要がある場合は、 StorageGRID システム全体で S3 オブジェクトのロックを有効にする必要があります。グローバルな S3 オブジェクトのロック設定を有効にすると、 S3 テナントユーザは S3 オブジェクトのロックでバケットとオブジェクトを作成および管理できるようになります。

.作業を開始する前に
* Root アクセス権限が割り当てられている。
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* S3オブジェクトロックのワークフローを確認し、考慮事項を理解しておきます。
* アクティブなILMポリシーのデフォルトルールが準拠していることを確認しました。を参照してください link:creating-default-ilm-rule.html["デフォルトの ILM ルールを作成します"] を参照してください。


.このタスクについて
テナントユーザが S3 オブジェクトのロックを有効にした新しいバケットを作成できるようにするには、グリッド管理者がグローバルな S3 オブジェクトロック設定を有効にする必要があります。この設定を有効にすると、無効にすることはできません。


NOTE: グローバル準拠設定は廃止されました。以前のバージョンのStorageGRID を使用してこの設定を有効にした場合、S3オブジェクトロック設定は自動的に有効になります。既存の準拠バケットの設定は引き続きStorageGRID を使用して管理できますが、新しい準拠バケットを作成することはできません。詳細については、を参照してください https://["ネットアップのナレッジベース： StorageGRID 11.5 でレガシー準拠バケットを管理する方法"^]。

.手順
. 設定 * > * System * > * S3 Object Lock * を選択します。
+
S3 Object Lock Settings （ S3 オブジェクトロック設定）ページが表示されます。

. S3 オブジェクトロックを有効にする * を選択します。
. * 適用 * を選択します。
+
確認のダイアログボックスが表示され、S3オブジェクトロックを有効にすると無効にできないことを示すメッセージが表示されます。

. システム全体に対して S3 オブジェクトロックを永続的に有効にしてもよろしいですか？ * OK * を選択します。
+
「 * OK * 」を選択した場合：

+
** アクティブなILMポリシーのデフォルトルールが準拠ルールの場合、S3オブジェクトロックはグリッド全体で有効になり、無効にすることはできません。
** デフォルトルールが準拠していない場合は、エラーが表示されます。準拠ルールをデフォルトルールとして含む新しいILMポリシーを作成してアクティブ化する必要があります。「 * OK 」を選択します。次に、新しいドラフトポリシーを作成してシミュレートし、アクティブ化します。を参照してください link:creating-ilm-policy.html["ILM ポリシーを作成する"] 手順については、を参照し




.完了後
S3オブジェクトロックのグローバル設定を有効にしたあとに、必要に応じて変更することができます link:creating-proposed-ilm-policy.html["新しいILMポリシーを作成します"]。設定を有効にすると、 ILM ポリシーに、準拠デフォルトルールと非準拠デフォルトルールの両方をオプションで含めることができます。たとえば、S3オブジェクトロックが有効になっていないバケット内のオブジェクトに対してフィルタが適用されていない非準拠ルールを使用できます。
