---
permalink: fabricpool/using-storagegrid-ilm-with-fabricpool-data.html 
sidebar: sidebar 
keywords: FabricPool, requirements, ILM, information lifecycle management, ILM rule, ILM rules, ILM policy, erasure-coding, replication, cloud storage pool, glacier 
summary: このシンプルなサンプルポリシーを、独自のILMルールとポリシーの出発点として使用できます。 
---
= FabricPool データ用のILMを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このシンプルなサンプルポリシーを、独自のILMルールとポリシーの出発点として使用できます。

この例では、コロラド州デンバーの 1 つのデータセンターに 4 つのストレージノードがある StorageGRID システムの ILM ルールと ILM ポリシーを設計していることを前提としています。この例のFabricPool データは、というバケットを使用しています `fabricpool-bucket`。


CAUTION: 以下の ILM ルールとポリシーは一例にすぎません。ILM ルールを設定する方法は多数あります。新しいポリシーをアクティブ化する前に、ドラフトポリシーをシミュレートして、コンテンツの損失を防ぐためにドラフトポリシーが想定どおりに機能することを確認してください。詳細については、を参照してください link:../ilm/index.html["ILM を使用してオブジェクトを管理する"]。

.作業を開始する前に
* を確認しておきます link:best-practices-ilm.html["FabricPool データでILMを使用するためのベストプラクティス"]。
* を使用して Grid Manager にサインインします link:../admin/web-browser-requirements.html["サポートされている Web ブラウザ"]。
* ILMまたはRoot Access権限が必要です。
* 以前のバージョンのStorageGRID からStorageGRID 11.7にアップグレードした場合は、使用するストレージプールが設定されています。通常は、StorageGRID サイトごとにストレージプールを作成する必要があります。
+

NOTE: この前提条件は、StorageGRID 11.7の新規インストールには適用されません。StorageGRID 11.7を新しいグリッドにインストールすると、サイトごとにストレージプールが自動的に作成されます。



.手順
. のデータにのみ適用されるILMルールを作成します `fabricpool-bucket`。次のルール例では、イレイジャーコーディングコピーを作成します。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2+1のイレイジャーコーディング（FabricPool データ用



 a| 
バケット名
 a| 
`fabricpool-bucket`

FabricPool テナントアカウントでフィルタリングすることもできます。



 a| 
高度なフィルタ
 a| 
オブジェクトサイズが0.2MBを超えています。

*注：* FabricPool は4MBのオブジェクトのみを書き込みますが、このルールではイレイジャーコーディングを使用するため、オブジェクトサイズフィルタを追加する必要があります。



 a| 
参照時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
From Day 0は永久に保存されます

デンバーの2+1 ECスキームを使用したイレイジャーコーディングによってオブジェクトを格納



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. 最初のルールに一致しないオブジェクトのレプリケートコピーを2つ作成するデフォルトのILMルールを作成します。基本フィルタ（テナントアカウントまたはバケット名）や高度なフィルタは選択しないでください。
+
[cols="1a,2a"]
|===
| ルール定義 | 値の例 


 a| 
ルール名
 a| 
2 つのレプリケートコピー



 a| 
バケット名
 a| 
_ なし _



 a| 
高度なフィルタ
 a| 
_ なし _



 a| 
参照時間
 a| 
取り込み時間



 a| 
期間と配置
 a| 
From Day 0は永久に保存されます

デンバーに2つのコピーをレプリケートしてオブジェクトを格納



 a| 
取り込み動作
 a| 
中間（ Balanced ）

|===
. ドラフトの ILM ポリシーを作成して 2 つのルールを選択レプリケーションルールではフィルタを使用しないため、ポリシーのデフォルト（最後の）ルールを使用できます。
. テストオブジェクトをグリッドに取り込みます。
. ポリシーをテストオブジェクトでシミュレートして動作を確認します。
. ポリシーをアクティブ化する。


このポリシーをアクティブ化すると、 StorageGRID はオブジェクトデータを次のように配置します。

* のFabricPool から階層化されたデータ `fabricpool-bucket` 2+1イレイジャーコーディングスキームを使用してイレイジャーコーディングされます。2 つのデータフラグメントと 1 つのパリティフラグメントが 3 つの異なるストレージノードに配置されます。
* 他のすべてのバケット内のオブジェクトがレプリケートされます。2 つのコピーが作成され、 2 つの異なるストレージノードに配置されます。
* イレイジャーコーディングコピーとレプリケートコピーは、ONTAP で削除されるまでStorageGRID に保持されます。StorageGRID ILM によってこれらの項目が削除されることはありません。

